// <auto-generated />
using System;
using AVR.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AVR.Infrastructure.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241016073843_new1")]
    partial class new1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AVR.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmailConfirmationOtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("OtpExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("725d7eba-1b70-43d1-a48e-82656991ef95"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            Avatar = "",
                            ConcurrencyStamp = "b056adcc-b5c1-4102-a9ac-caa4acb809c7",
                            Email = "quansongngu13@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Quan",
                            NormalizedEmail = "QUANSONGNGU13@GMAIL.COM",
                            NormalizedUserName = "QUANSONGNGU13@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEElhkkTUB4WBiQm6rxxWv7f77mEAyuRxiPYEnBZ7L560yzhDMzB4xWLBDhhsdYkltw==",
                            PhoneNumber = "0949035672",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "816f5625-712d-4cbe-8d47-1beb22b35b65",
                            TwoFactorEnabled = false,
                            UserName = "quansongngu13@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("70ab5bdb-5c8d-44f6-8834-652bf0af5427"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            ConcurrencyStamp = "e347cd88-86f1-4bcd-8595-c4041ab4fa77",
                            Email = "johndoe@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "John Doe",
                            NormalizedEmail = "JOHNDOE@EXAMPLE.COM",
                            NormalizedUserName = "JOHNDOE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIbDRWWDdlTyIHIiViMsT0xZotAX7oINdRaEcFj9sEOViAl/hfVDGhdNfWWheshtZA==",
                            PhoneNumber = "123456789",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "bbd1c2b6-5445-43e3-bc8f-ce70bac48dc4",
                            TwoFactorEnabled = false,
                            UserName = "johndoe@example.com"
                        },
                        new
                        {
                            Id = new Guid("b01af5e0-9cd4-4a93-902d-a207cee93f91"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            Avatar = "",
                            ConcurrencyStamp = "8e9ccb9a-f11f-4424-816d-23d508cb56ad",
                            Email = "michael.smith@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Michael Smith",
                            NormalizedEmail = "MICHAEL.SMITH@EXAMPLE.COM",
                            NormalizedUserName = "MICHAEL.SMITH@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEo25uQeaWKAwVuWracXYL+JV10zriiV7QqIPINwRMbgrEuVDCqU7TAwCOlDyOGnMg==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "6ada9e26-a06d-4361-b418-55a58a77ab6a",
                            TwoFactorEnabled = false,
                            UserName = "michael.smith@example.com"
                        },
                        new
                        {
                            Id = new Guid("0c0e7cff-70d0-413c-9882-d6db70b34858"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            Avatar = "",
                            ConcurrencyStamp = "ecfc0dc8-7efd-43a6-bb9b-d397806feadf",
                            Email = "luong.a11.dbk@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Duc Luong",
                            NormalizedEmail = "LUONG.A11.DBK@GMAIL.COM",
                            NormalizedUserName = "LUONG.A11.DBK@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOE46c9gmE3B948nURikJ7LMwh0F938Onp8xjX6Y5SqYBiuSLA+4/9jOiAoeCqUt4A==",
                            PhoneNumber = "0987654321",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "88f5b884-6720-4a27-bcac-18339fc6f30c",
                            TwoFactorEnabled = false,
                            UserName = "luong.a11.dbk@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("be7837f4-9990-471a-a1c4-8e1c47f05e02"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            Avatar = "",
                            ConcurrencyStamp = "aab5095e-6324-42a6-a192-138285b50d21",
                            Email = "david.brown@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "David Brown",
                            NormalizedEmail = "DAVID.BROWN@EXAMPLE.COM",
                            NormalizedUserName = "DAVID.BROWN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECl2RTPDax1Zpe9pcb+0yZnk/lDYo6jqBAG+slwLJmu2v7vo+ra4zzM723404Vmnbw==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "b8a0d1c9-36d3-4cba-8574-859a541d156c",
                            TwoFactorEnabled = false,
                            UserName = "david.brown@example.com"
                        },
                        new
                        {
                            Id = new Guid("a38fecd7-e213-4549-a14a-79c179438401"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            Avatar = "",
                            ConcurrencyStamp = "23005ddd-505f-4177-9b64-042a76934991",
                            Email = "construction.corp@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Construction Corp",
                            NormalizedEmail = "CONSTRUCTION.CORP@EXAMPLE.COM",
                            NormalizedUserName = "CONSTRUCTION.CORP@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGX9qoizjoQGWqLZd5HvJ/OsRr7ZLJN6+5hvsZguc6r55je69xaBWzC4YvrgOQQc3g==",
                            PhoneNumber = "0987654321",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "6ba7e377-296e-4e64-8144-1f9d48e17473",
                            TwoFactorEnabled = false,
                            UserName = "construction.corp@example.com"
                        },
                        new
                        {
                            Id = new Guid("81db916c-ff09-4306-a8d7-bdac138a0e0e"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            ConcurrencyStamp = "3dce6d72-a1f4-4007-8589-c672d0c93c52",
                            Email = "alice.smith@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Alice Smith",
                            NormalizedEmail = "ALICE.SMITH@EXAMPLE.COM",
                            NormalizedUserName = "ALICE.SMITH@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA3r5cKcEZqp2/1uTmsq/NuTys3A8D5QjGZY6Ccf+E2x9HtwbMUk4W1a973mcbzGvg==",
                            PhoneNumber = "0901234567",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "0ab32540-bde8-4e02-b914-9d3f7cfc1d66",
                            TwoFactorEnabled = false,
                            UserName = "alice.smith@example.com"
                        },
                        new
                        {
                            Id = new Guid("09eda817-dfe5-43e4-9992-2af384e468d0"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            ConcurrencyStamp = "9741215c-08e6-4c54-b7d9-29c98a389f25",
                            Email = "bob.johnson@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Bob Johnson",
                            NormalizedEmail = "BOB.JOHNSON@EXAMPLE.COM",
                            NormalizedUserName = "BOB.JOHNSON@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAFrr8yOJMWtrt/FPqoh1s9CwP+YrXOzBaqB8G/orhtdnTaoIN83V3n6lLK3gj4hog==",
                            PhoneNumber = "0902345678",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "7730de90-ec0d-4b5f-8956-9b23b72b610c",
                            TwoFactorEnabled = false,
                            UserName = "bob.johnson@example.com"
                        },
                        new
                        {
                            Id = new Guid("dd7759be-09a7-4f50-bd4c-04d5cc6d61ad"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            ConcurrencyStamp = "d80ee631-d25e-47c2-9e30-530021da3751",
                            Email = "charlie.brown@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Charlie Brown",
                            NormalizedEmail = "CHARLIE.BROWN@EXAMPLE.COM",
                            NormalizedUserName = "CHARLIE.BROWN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECHcI9N/EgvbIXKJ23LAeI64uOxl3o9/n8pb87usFlDMXrFjC+WL//ITbiE25ZqWbw==",
                            PhoneNumber = "0903456789",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "d9dabeb8-5634-459e-a063-847caf5e129f",
                            TwoFactorEnabled = false,
                            UserName = "charlie.brown@example.com"
                        },
                        new
                        {
                            Id = new Guid("c1e3a0f1-a89a-466b-9b77-f3b37f519853"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            ConcurrencyStamp = "387c755b-9ded-4c71-9a14-16ea294fc233",
                            Email = "diana.prince@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Diana Prince",
                            NormalizedEmail = "DIANA.PRINCE@EXAMPLE.COM",
                            NormalizedUserName = "DIANA.PRINCE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIweotDzlhfoGnIEY9L/IPlkuPhSjnyOqrt06/oT3jBmV+BpglN40HY6c87iCAmL3g==",
                            PhoneNumber = "0904567890",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "f74c2722-c7b2-4809-8de4-e618b34aafc5",
                            TwoFactorEnabled = false,
                            UserName = "diana.prince@example.com"
                        },
                        new
                        {
                            Id = new Guid("ba5804ff-1ca7-4545-a7b4-09f4039da8f3"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            ConcurrencyStamp = "58e58421-74e5-4a62-a5ab-4cea9cc8caa9",
                            Email = "eve.adams@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Eve Adams",
                            NormalizedEmail = "EVE.ADAMS@EXAMPLE.COM",
                            NormalizedUserName = "EVE.ADAMS@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMaqkV2ZTZ7OAXRfGjjjP8J9vdMPTzfQ9KCrR1WRh91dDbt+9h0Te45cuSbC/jJFhA==",
                            PhoneNumber = "0905678901",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "2c92b89f-ae80-43d4-9242-5fd46c8f4c3a",
                            TwoFactorEnabled = false,
                            UserName = "eve.adams@example.com"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.AccountRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("67fc29a3-84cb-435f-954d-274df8a4b9da"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("263aaf82-0cf6-406b-a592-35932136fadb"),
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = new Guid("6aa5ade6-6c00-4194-a9eb-13316851ad43"),
                            Name = "Apartment Owner",
                            NormalizedName = "APARTMENT OWNER"
                        },
                        new
                        {
                            Id = new Guid("c0634a9c-81a0-4417-8566-c90d5b395569"),
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        },
                        new
                        {
                            Id = new Guid("11789c78-48f3-44f6-81b4-4c5e0f133161"),
                            Name = "Management",
                            NormalizedName = "MANAGEMENT"
                        },
                        new
                        {
                            Id = new Guid("15a832c3-b547-45b7-b43e-bde1100278bf"),
                            Name = "Project Provider",
                            NormalizedName = "PROJECT PROVIDER"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.AgreementUpdateRequest", b =>
                {
                    b.Property<Guid>("AgreementUpdateRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentProjectProviderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RequestDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RequestDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AgreementUpdateRequestID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ApartmentProjectProviderID");

                    b.ToTable("AgreementUpdateRequests");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentFacility", b =>
                {
                    b.Property<Guid>("ApartmentFacilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacilityID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApartmentFacilityID");

                    b.HasIndex("ApartmentID");

                    b.HasIndex("FacilityID");

                    b.ToTable("ApartmentFacilitys");

                    b.HasData(
                        new
                        {
                            ApartmentFacilityID = new Guid("075d2c24-68c8-4009-94da-da9365cf5e51"),
                            ApartmentID = new Guid("6850cdfa-e1b4-446d-aecc-20d006ce15da"),
                            FacilityID = new Guid("233ab990-430d-45c8-bbc8-0a32c478c691")
                        },
                        new
                        {
                            ApartmentFacilityID = new Guid("1dc50feb-3517-4004-bfb6-78222836733a"),
                            ApartmentID = new Guid("a04025d0-f385-4993-a1e0-a0ea65c1f989"),
                            FacilityID = new Guid("2a730eff-8dc5-42fb-a2a5-07f880bdb8e8")
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentImage", b =>
                {
                    b.Property<Guid>("ApartmentImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ApartmentImageID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("ApartmentImages");

                    b.HasData(
                        new
                        {
                            ApartmentImageID = new Guid("bc934192-1fd3-4bb3-b0bd-05178f08d3c2"),
                            ApartmentID = new Guid("6850cdfa-e1b4-446d-aecc-20d006ce15da"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9573), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Living Room View",
                            ImageUrl = "https://example.com/apartment1-livingroom.jpg",
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9575), new TimeSpan(0, 7, 0, 0, 0))
                        },
                        new
                        {
                            ApartmentImageID = new Guid("5fdc6f6f-f313-4ef2-8b8b-d55647199e8a"),
                            ApartmentID = new Guid("6850cdfa-e1b4-446d-aecc-20d006ce15da"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9578), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bedroom View",
                            ImageUrl = "https://example.com/apartment1-bedroom.jpg",
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9578), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentInteraction", b =>
                {
                    b.Property<Guid>("ApartmentInteractionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("InteractionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("InteractionTypes")
                        .HasColumnType("int");

                    b.HasKey("ApartmentInteractionID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("ApartmentInteractions");

                    b.HasData(
                        new
                        {
                            ApartmentInteractionID = new Guid("9e9766f6-03a0-473f-8924-c6a7f115460d"),
                            AccountID = new Guid("81db916c-ff09-4306-a8d7-bdac138a0e0e"),
                            ApartmentID = new Guid("6850cdfa-e1b4-446d-aecc-20d006ce15da"),
                            InteractionDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9751), new TimeSpan(0, 7, 0, 0, 0)),
                            InteractionTypes = 0
                        },
                        new
                        {
                            ApartmentInteractionID = new Guid("606c1244-6ee0-49d3-9f0d-3e600b49aa75"),
                            AccountID = new Guid("09eda817-dfe5-43e4-9992-2af384e468d0"),
                            ApartmentID = new Guid("a04025d0-f385-4993-a1e0-a0ea65c1f989"),
                            InteractionDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9761), new TimeSpan(0, 7, 0, 0, 0)),
                            InteractionTypes = 1
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentOwnerApartment", b =>
                {
                    b.Property<Guid>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocumentID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("ApartmentOwnerApartment");

                    b.HasData(
                        new
                        {
                            DocumentID = new Guid("0237b5f6-d89e-4ef9-b2bf-781ec2663052"),
                            AccountID = new Guid("be7837f4-9990-471a-a1c4-8e1c47f05e02"),
                            ApartmentID = new Guid("6850cdfa-e1b4-446d-aecc-20d006ce15da")
                        },
                        new
                        {
                            DocumentID = new Guid("85d554b0-a84e-45f7-9ccf-710a637b8a7f"),
                            AccountID = new Guid("be7837f4-9990-471a-a1c4-8e1c47f05e02"),
                            ApartmentID = new Guid("6850cdfa-e1b4-446d-aecc-20d006ce15da")
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentProjectProvider", b =>
                {
                    b.Property<Guid>("ApartmentProjectProviderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApartmentProjectDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApartmentProjectProviderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DiagramUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegallInfor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ApartmentProjectProviderID");

                    b.HasIndex("AccountID")
                        .IsUnique();

                    b.ToTable("ApartmentProjectProvider");

                    b.HasData(
                        new
                        {
                            ApartmentProjectProviderID = new Guid("27279ccb-44bc-4603-bb16-3e1e7771a5eb"),
                            AccountID = new Guid("a38fecd7-e213-4549-a14a-79c179438401"),
                            ApartmentProjectDescription = "A provider of luxury high-end apartments.",
                            ApartmentProjectProviderName = "High-End Apartment Provider",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(8352), new TimeSpan(0, 7, 0, 0, 0)),
                            DiagramUrl = "https://example.com/diagram.png",
                            LegallInfor = "Legal Information",
                            Location = "City Center",
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(8352), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApartmentOwnerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AppointmentDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("AppointmentStatus")
                        .HasColumnType("int");

                    b.Property<int>("AppointmentTypes")
                        .HasColumnType("int");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("AssignedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProjectProviderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SlotID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaffID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AppointmentID");

                    b.HasIndex("ApartmentID");

                    b.HasIndex("ApartmentOwnerID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ProjectProviderID");

                    b.HasIndex("SlotID");

                    b.HasIndex("StaffID");

                    b.ToTable("Appointment");

                    b.HasData(
                        new
                        {
                            AppointmentID = new Guid("632b0f19-957d-47ad-ae76-03a7bcd872b7"),
                            ApartmentID = new Guid("6850cdfa-e1b4-446d-aecc-20d006ce15da"),
                            ApartmentOwnerID = new Guid("be7837f4-9990-471a-a1c4-8e1c47f05e02"),
                            AppointmentDate = new DateTimeOffset(new DateTime(2024, 10, 17, 14, 38, 41, 369, DateTimeKind.Unspecified).AddTicks(31), new TimeSpan(0, 7, 0, 0, 0)),
                            AppointmentStatus = 1,
                            AppointmentTypes = 1,
                            AssignedBy = "Admin",
                            AssignedDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9992), new TimeSpan(0, 7, 0, 0, 0)),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9990), new TimeSpan(0, 7, 0, 0, 0)),
                            CustomerID = new Guid("ba5804ff-1ca7-4545-a7b4-09f4039da8f3"),
                            Description = "Schedule a viewing for the Skyline Apartment.",
                            ProjectProviderID = new Guid("a38fecd7-e213-4549-a14a-79c179438401"),
                            SlotID = new Guid("ecbae07b-1a0d-4ccf-8ebe-d594e3a87756"),
                            StaffID = new Guid("70ab5bdb-5c8d-44f6-8834-652bf0af5427"),
                            Title = "Viewing Appointment for Skyline Apartment",
                            UpdatedDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9991), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.Deposit", b =>
                {
                    b.Property<Guid>("DepositID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DepositStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("constractNumber")
                        .HasColumnType("float");

                    b.Property<double>("depositAmount")
                        .HasColumnType("float");

                    b.Property<double>("depositPercentage")
                        .HasColumnType("float");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("expiryDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepositID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("DepositRequest");

                    b.HasData(
                        new
                        {
                            DepositID = new Guid("6fc05dab-148f-416c-9e99-fa4ed227d8ea"),
                            AccountID = new Guid("dd7759be-09a7-4f50-bd4c-04d5cc6d61ad"),
                            ApartmentID = new Guid("6850cdfa-e1b4-446d-aecc-20d006ce15da"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 369, DateTimeKind.Unspecified).AddTicks(109), new TimeSpan(0, 7, 0, 0, 0)),
                            DepositStatus = 0,
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 369, DateTimeKind.Unspecified).AddTicks(113), new TimeSpan(0, 7, 0, 0, 0)),
                            constractNumber = 12345.0,
                            depositAmount = 50000.0,
                            depositPercentage = 20.0,
                            description = "Deposit for Skyline Apartment.",
                            expiryDate = new DateTimeOffset(new DateTime(2024, 11, 16, 14, 38, 41, 369, DateTimeKind.Unspecified).AddTicks(114), new TimeSpan(0, 7, 0, 0, 0)),
                            note = "Initial deposit for apartment"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositCancel", b =>
                {
                    b.Property<Guid>("DepositCancelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CancelDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DepositCancelTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepositID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecoveryPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("RefundDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("updateAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("DepositCancelID");

                    b.HasIndex("AccountID");

                    b.HasIndex("DepositCancelTypeID");

                    b.HasIndex("DepositID");

                    b.ToTable("DepositCancel");

                    b.HasData(
                        new
                        {
                            DepositCancelID = new Guid("cdec533b-2a40-46e2-86e2-8dbcd4f4d36a"),
                            AccountID = new Guid("0c0e7cff-70d0-413c-9882-d6db70b34858"),
                            CancelDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 369, DateTimeKind.Unspecified).AddTicks(226), new TimeSpan(0, 7, 0, 0, 0)),
                            DepositCancelTypeID = new Guid("d380a78e-2046-4666-be05-27c768bcf3f2"),
                            DepositID = new Guid("6fc05dab-148f-416c-9e99-fa4ed227d8ea"),
                            RecoveryPrice = "45000",
                            RefundDate = new DateTimeOffset(new DateTime(2024, 10, 21, 14, 38, 41, 369, DateTimeKind.Unspecified).AddTicks(227), new TimeSpan(0, 7, 0, 0, 0)),
                            updateAt = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 369, DateTimeKind.Unspecified).AddTicks(228), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositCancelType", b =>
                {
                    b.Property<Guid>("DepositCancelTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DepositCancelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("DepositCancelTypeID");

                    b.ToTable("DepositCancelTypes");

                    b.HasData(
                        new
                        {
                            DepositCancelTypeID = new Guid("d380a78e-2046-4666-be05-27c768bcf3f2"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 369, DateTimeKind.Unspecified).AddTicks(75), new TimeSpan(0, 7, 0, 0, 0)),
                            DepositCancelName = "Customer Request",
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 369, DateTimeKind.Unspecified).AddTicks(76), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.Facilities", b =>
                {
                    b.Property<Guid>("FacilitiesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacilitiesDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilitiesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FacilitiesID");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            FacilitiesID = new Guid("233ab990-430d-45c8-bbc8-0a32c478c691"),
                            FacilitiesDescription = "A large outdoor swimming pool.",
                            FacilitiesName = "Swimming Pool"
                        },
                        new
                        {
                            FacilitiesID = new Guid("2a730eff-8dc5-42fb-a2a5-07f880bdb8e8"),
                            FacilitiesDescription = "A fully equipped fitness gym.",
                            FacilitiesName = "Gym"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeedbackStatus")
                        .HasColumnType("int");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeedbackID");

                    b.HasIndex("AccountID");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            FeedbackID = new Guid("58e757ea-9618-40e6-996e-1194c0d3acd0"),
                            AccountID = new Guid("81db916c-ff09-4306-a8d7-bdac138a0e0e"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 369, DateTimeKind.Unspecified).AddTicks(265), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "I really enjoyed the experience. Highly recommend!",
                            FeedbackStatus = 0,
                            Rating = 5f,
                            Title = "Great Service!"
                        },
                        new
                        {
                            FeedbackID = new Guid("72f66510-9183-48f6-ba0c-81c0e042119f"),
                            AccountID = new Guid("09eda817-dfe5-43e4-9992-2af384e468d0"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 369, DateTimeKind.Unspecified).AddTicks(269), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "The service was okay, but there's room for improvement.",
                            FeedbackStatus = 0,
                            Rating = 3.5f,
                            Title = "Could be better"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("NotificationStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("NotificationTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReferenceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("NotificationID");

                    b.HasIndex("AccountID");

                    b.HasIndex("NotificationTypeID");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            NotificationID = new Guid("0ee49060-61c0-4c89-a67f-8319e1ecdc5d"),
                            AccountID = new Guid("dd7759be-09a7-4f50-bd4c-04d5cc6d61ad"),
                            Created = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 369, DateTimeKind.Unspecified).AddTicks(338), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Thank you for joining us! We hope you enjoy your experience.",
                            IsRead = false,
                            NotificationStatus = 0,
                            NotificationTypeID = new Guid("13c10f30-047a-4d9a-9c07-229bd44234f5"),
                            ReferenceID = new Guid("36791dba-b9d5-460b-84fb-36b2a031015a"),
                            Title = "Welcome to Our Service",
                            Updated = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 369, DateTimeKind.Unspecified).AddTicks(340), new TimeSpan(0, 7, 0, 0, 0))
                        },
                        new
                        {
                            NotificationID = new Guid("e7502c92-9d09-4abb-a860-1179c4aa9fd9"),
                            AccountID = new Guid("09eda817-dfe5-43e4-9992-2af384e468d0"),
                            Created = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 369, DateTimeKind.Unspecified).AddTicks(348), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Check out our new feature that enhances your experience!",
                            IsRead = false,
                            NotificationStatus = 0,
                            NotificationTypeID = new Guid("13c10f30-047a-4d9a-9c07-229bd44234f5"),
                            ReferenceID = new Guid("e53937ff-a1a0-4ccb-be39-272d1aa36fdb"),
                            Title = "New Feature Available",
                            Updated = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 369, DateTimeKind.Unspecified).AddTicks(349), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.NotificationType", b =>
                {
                    b.Property<Guid>("NotificationTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NotificationTypeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationTypeID");

                    b.ToTable("NotificationTypes");

                    b.HasData(
                        new
                        {
                            NotificationTypeID = new Guid("13c10f30-047a-4d9a-9c07-229bd44234f5"),
                            NotificationTypeDescription = "General notifications for users.",
                            NotificationTypeName = "General"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectAccessLog", b =>
                {
                    b.Property<Guid>("ProjectAccessLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("accessDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ProjectAccessLogID");

                    b.HasIndex("ProjectApartmentID");

                    b.ToTable("ProjectAccessLogs");

                    b.HasData(
                        new
                        {
                            ProjectAccessLogID = new Guid("677690df-1dc6-4d49-90b7-4e068d047407"),
                            ProjectApartmentID = new Guid("0e5b0cea-46d8-4624-846d-18660bf2d7d0"),
                            accessDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9167), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectImage", b =>
                {
                    b.Property<Guid>("ProjectImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectImageID");

                    b.HasIndex("ProjectApartmentID");

                    b.ToTable("ProjectImages");

                    b.HasData(
                        new
                        {
                            ProjectImageID = new Guid("602ec84d-5a71-431c-a8c4-827ad8f4b9f6"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9223), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Image of the luxury apartment",
                            Name = "Luxury Apartment Image",
                            ProjectApartmentID = new Guid("0e5b0cea-46d8-4624-846d-18660bf2d7d0"),
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9224), new TimeSpan(0, 7, 0, 0, 0)),
                            Url = "https://example.com/luxury-apartment.jpg"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.RequestApartment", b =>
                {
                    b.Property<Guid>("RequestApartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ResponseDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ResponseMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestApartmentID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("RequestApartments");

                    b.HasData(
                        new
                        {
                            RequestApartmentID = new Guid("8ac08d20-3227-4077-8ea7-6baeb113fa3c"),
                            AccountID = new Guid("09eda817-dfe5-43e4-9992-2af384e468d0"),
                            ApartmentID = new Guid("6850cdfa-e1b4-446d-aecc-20d006ce15da"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9816), new TimeSpan(0, 7, 0, 0, 0)),
                            Note = "Please respond as soon as possible.",
                            RequestMessage = "I would like to know more about this apartment.",
                            ResponseDate = new DateTimeOffset(new DateTime(2024, 10, 17, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9817), new TimeSpan(0, 7, 0, 0, 0)),
                            ResponseMessage = "Your request has been received."
                        },
                        new
                        {
                            RequestApartmentID = new Guid("025bea0e-2f81-403a-b8cc-6f8cd4ac13fd"),
                            AccountID = new Guid("81db916c-ff09-4306-a8d7-bdac138a0e0e"),
                            ApartmentID = new Guid("a04025d0-f385-4993-a1e0-a0ea65c1f989"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9825), new TimeSpan(0, 7, 0, 0, 0)),
                            Note = "Looking forward to your response.",
                            RequestMessage = "Is this apartment still available for booking?",
                            ResponseDate = new DateTimeOffset(new DateTime(2024, 10, 17, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9826), new TimeSpan(0, 7, 0, 0, 0)),
                            ResponseMessage = "The apartment is still available."
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.Slot", b =>
                {
                    b.Property<Guid>("SlotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SlotID");

                    b.ToTable("Slots");

                    b.HasData(
                        new
                        {
                            SlotID = new Guid("ecbae07b-1a0d-4ccf-8ebe-d594e3a87756"),
                            EndTime = "10:00 AM",
                            StartTime = "09:00 AM"
                        },
                        new
                        {
                            SlotID = new Guid("b29b77e6-3bc2-4725-b6be-be2055e0a558"),
                            EndTime = "11:00 AM",
                            StartTime = "10:00 AM"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DepositID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PaymentMethods")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TransactionStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("ammount")
                        .HasColumnType("float");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionID");

                    b.HasIndex("DepositID")
                        .IsUnique();

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionID = new Guid("e1176b91-abc4-4510-9385-547a87d91dac"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 369, DateTimeKind.Unspecified).AddTicks(182), new TimeSpan(0, 7, 0, 0, 0)),
                            DepositID = new Guid("6fc05dab-148f-416c-9e99-fa4ed227d8ea"),
                            PaymentMethods = 0,
                            TransactionDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 369, DateTimeKind.Unspecified).AddTicks(184), new TimeSpan(0, 7, 0, 0, 0)),
                            TransactionStatus = 0,
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 369, DateTimeKind.Unspecified).AddTicks(184), new TimeSpan(0, 7, 0, 0, 0)),
                            ammount = 50000.0,
                            description = "Payment for initial deposit.",
                            note = "Deposit payment"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.VRExperience", b =>
                {
                    b.Property<Guid>("VRExperienceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("video_url_file")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VRExperienceID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("VRExperiences");

                    b.HasData(
                        new
                        {
                            VRExperienceID = new Guid("67daf259-53f1-4e21-b5f4-627c991ab00d"),
                            AccountID = new Guid("70ab5bdb-5c8d-44f6-8834-652bf0af5427"),
                            ApartmentID = new Guid("6850cdfa-e1b4-446d-aecc-20d006ce15da"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9640), new TimeSpan(0, 7, 0, 0, 0)),
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9648), new TimeSpan(0, 7, 0, 0, 0)),
                            video_url_file = "https://example.com/vr-experience1.mp4"
                        },
                        new
                        {
                            VRExperienceID = new Guid("2b4218b3-4a61-4a95-bcdd-db4d73260e80"),
                            AccountID = new Guid("70ab5bdb-5c8d-44f6-8834-652bf0af5427"),
                            ApartmentID = new Guid("a04025d0-f385-4993-a1e0-a0ea65c1f989"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9671), new TimeSpan(0, 7, 0, 0, 0)),
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9672), new TimeSpan(0, 7, 0, 0, 0)),
                            video_url_file = "https://example.com/vr-experience2.mp4"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.VR_Access_Log", b =>
                {
                    b.Property<Guid>("VR_Access_LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("VRExperienceID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VR_Access_LogID");

                    b.HasIndex("VRExperienceID");

                    b.ToTable("VR_Access_Logs");

                    b.HasData(
                        new
                        {
                            VR_Access_LogID = new Guid("b554fa82-336f-4cef-af7a-959f50994969"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9711), new TimeSpan(0, 7, 0, 0, 0)),
                            VRExperienceID = new Guid("67daf259-53f1-4e21-b5f4-627c991ab00d")
                        },
                        new
                        {
                            VR_Access_LogID = new Guid("9d5b9488-3dc0-4192-9e7e-861ac1cbfb5b"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9714), new TimeSpan(0, 7, 0, 0, 0)),
                            VRExperienceID = new Guid("2b4218b3-4a61-4a95-bcdd-db4d73260e80")
                        });
                });

            modelBuilder.Entity("Apartment", b =>
                {
                    b.Property<Guid>("ApartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApartmentStatus")
                        .HasColumnType("int");

                    b.Property<int>("ApartmentType")
                        .HasColumnType("int");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("BalconyDirection")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ExpiryDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfBathrooms")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfRooms")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerSquareMeter")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("ProjectApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RecommendedPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApartmentID");

                    b.HasIndex("ProjectApartmentID");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            ApartmentID = new Guid("6850cdfa-e1b4-446d-aecc-20d006ce15da"),
                            Address = "123 Skyline Road, New City",
                            ApartmentName = "Skyline Apartment",
                            ApartmentStatus = 0,
                            ApartmentType = 1,
                            Area = 150.00m,
                            BalconyDirection = 5,
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9272), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "A modern apartment with a skyline view.",
                            Direction = 1,
                            District = "",
                            ExpiryDate = new DateTimeOffset(new DateTime(2029, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9285), new TimeSpan(0, 7, 0, 0, 0)),
                            Location = "City Center",
                            NumberOfBathrooms = 2,
                            NumberOfRooms = 3,
                            PricePerSquareMeter = 70000000m,
                            ProjectApartmentID = new Guid("0e5b0cea-46d8-4624-846d-18660bf2d7d0"),
                            RecommendedPrice = 10000000000m,
                            UpdatedDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9273), new TimeSpan(0, 7, 0, 0, 0)),
                            Ward = ""
                        },
                        new
                        {
                            ApartmentID = new Guid("a04025d0-f385-4993-a1e0-a0ea65c1f989"),
                            Address = "456 Ocean Drive, Coastal City",
                            ApartmentName = "Ocean View Apartment",
                            ApartmentStatus = 2,
                            ApartmentType = 2,
                            Area = 170.00m,
                            BalconyDirection = 8,
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9304), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "A luxurious apartment with an ocean view.",
                            Direction = 2,
                            District = "",
                            ExpiryDate = new DateTimeOffset(new DateTime(2027, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9307), new TimeSpan(0, 7, 0, 0, 0)),
                            Location = "Beachfront",
                            NumberOfBathrooms = 3,
                            NumberOfRooms = 4,
                            PricePerSquareMeter = 90000000m,
                            ProjectApartmentID = new Guid("0e5b0cea-46d8-4624-846d-18660bf2d7d0"),
                            RecommendedPrice = 15000000000m,
                            UpdatedDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(9304), new TimeSpan(0, 7, 0, 0, 0)),
                            Ward = ""
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("725d7eba-1b70-43d1-a48e-82656991ef95"),
                            RoleId = new Guid("67fc29a3-84cb-435f-954d-274df8a4b9da")
                        },
                        new
                        {
                            UserId = new Guid("b01af5e0-9cd4-4a93-902d-a207cee93f91"),
                            RoleId = new Guid("263aaf82-0cf6-406b-a592-35932136fadb")
                        },
                        new
                        {
                            UserId = new Guid("be7837f4-9990-471a-a1c4-8e1c47f05e02"),
                            RoleId = new Guid("6aa5ade6-6c00-4194-a9eb-13316851ad43")
                        },
                        new
                        {
                            UserId = new Guid("70ab5bdb-5c8d-44f6-8834-652bf0af5427"),
                            RoleId = new Guid("c0634a9c-81a0-4417-8566-c90d5b395569")
                        },
                        new
                        {
                            UserId = new Guid("0c0e7cff-70d0-413c-9882-d6db70b34858"),
                            RoleId = new Guid("11789c78-48f3-44f6-81b4-4c5e0f133161")
                        },
                        new
                        {
                            UserId = new Guid("a38fecd7-e213-4549-a14a-79c179438401"),
                            RoleId = new Guid("15a832c3-b547-45b7-b43e-bde1100278bf")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectApartment", b =>
                {
                    b.Property<Guid>("ProjectApartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentProjectProviderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Price_range")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectApartmentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectApartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectApartmentStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ProjectApartmentID");

                    b.HasIndex("AccountId");

                    b.HasIndex("ApartmentProjectProviderID");

                    b.ToTable("ProjectApartments");

                    b.HasData(
                        new
                        {
                            ProjectApartmentID = new Guid("0e5b0cea-46d8-4624-846d-18660bf2d7d0"),
                            ApartmentProjectProviderID = new Guid("27279ccb-44bc-4603-bb16-3e1e7771a5eb"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(8505), new TimeSpan(0, 7, 0, 0, 0)),
                            Price_range = "500,000 - 1,000,000 USD",
                            ProjectApartmentDescription = "A spacious luxury apartment with modern amenities.",
                            ProjectApartmentName = "Luxury Apartment",
                            ProjectApartmentStatus = 0,
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 14, 38, 41, 368, DateTimeKind.Unspecified).AddTicks(8506), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.AgreementUpdateRequest", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("AgreementUpdateRequests")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.ApartmentProjectProvider", "ApartmentProjectProvider")
                        .WithMany("AgreementUpdateRequests")
                        .HasForeignKey("ApartmentProjectProviderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("ApartmentProjectProvider");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentFacility", b =>
                {
                    b.HasOne("Apartment", "Apartment")
                        .WithMany("ApartmentFacilities")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Facilities", "Facility")
                        .WithMany("ApartmentFacilities")
                        .HasForeignKey("FacilityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentImage", b =>
                {
                    b.HasOne("Apartment", "Apartments")
                        .WithMany("ApartmentImages")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentInteraction", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("ApartmentInteractions")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apartment", "Apartments")
                        .WithMany("ApartmentInteractions")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentOwnerApartment", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Account")
                        .WithMany("ApartmentOwnerApartments")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apartment", "Apartment")
                        .WithMany("ApartmentOwnerApartments")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentProjectProvider", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithOne("ApartmentProjectProviders")
                        .HasForeignKey("AVR.Domain.Entities.ApartmentProjectProvider", "AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Apartment", "Apartments")
                        .WithMany("Appointments")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Account", "ApartmentOwner")
                        .WithMany("Appointments")
                        .HasForeignKey("ApartmentOwnerID");

                    b.HasOne("AVR.Domain.Entities.Account", "Customer")
                        .WithMany("CustomerAppointments")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AVR.Domain.Entities.Account", "ProjectProvider")
                        .WithMany("ProjectProviderAppointments")
                        .HasForeignKey("ProjectProviderID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AVR.Domain.Entities.Slot", "Slots")
                        .WithMany("Appointments")
                        .HasForeignKey("SlotID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Account", "Staff")
                        .WithMany("StaffAppointments")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApartmentOwner");

                    b.Navigation("Apartments");

                    b.Navigation("Customer");

                    b.Navigation("ProjectProvider");

                    b.Navigation("Slots");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Deposit", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("Deposits")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apartment", "Apartments")
                        .WithMany("Deposits")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositCancel", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("DepositCancels")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.DepositCancelType", "DepositCancelTypes")
                        .WithMany("DepositCancels")
                        .HasForeignKey("DepositCancelTypeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Deposit", "Deposits")
                        .WithMany("DepositCancels")
                        .HasForeignKey("DepositID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("DepositCancelTypes");

                    b.Navigation("Deposits");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("Feedbacks")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Notification", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.NotificationType", "NotificationTypes")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("NotificationTypes");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectAccessLog", b =>
                {
                    b.HasOne("ProjectApartment", "ProjectApartments")
                        .WithMany("ProjectAccessLogs")
                        .HasForeignKey("ProjectApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProjectApartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectImage", b =>
                {
                    b.HasOne("ProjectApartment", "ProjectApartments")
                        .WithMany("ProjectImages")
                        .HasForeignKey("ProjectApartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectApartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.RequestApartment", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("RequestApartments")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apartment", "Apartments")
                        .WithMany("RequestApartments")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Deposit", "Deposits")
                        .WithOne("Transactions")
                        .HasForeignKey("AVR.Domain.Entities.Transaction", "DepositID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deposits");
                });

            modelBuilder.Entity("AVR.Domain.Entities.VRExperience", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("VRExperiences")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apartment", "Apartments")
                        .WithMany("VRExperiences")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.VR_Access_Log", b =>
                {
                    b.HasOne("AVR.Domain.Entities.VRExperience", "VRExperiences")
                        .WithMany("VR_Access_Logs")
                        .HasForeignKey("VRExperienceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("VRExperiences");
                });

            modelBuilder.Entity("Apartment", b =>
                {
                    b.HasOne("ProjectApartment", "ProjectApartment")
                        .WithMany("Apartments")
                        .HasForeignKey("ProjectApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProjectApartment");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.AccountRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.AccountRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectApartment", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany("ProjectApartments")
                        .HasForeignKey("AccountId");

                    b.HasOne("AVR.Domain.Entities.ApartmentProjectProvider", "ApartmentProjectProvider")
                        .WithMany("ProjectApartments")
                        .HasForeignKey("ApartmentProjectProviderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApartmentProjectProvider");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Account", b =>
                {
                    b.Navigation("AgreementUpdateRequests");

                    b.Navigation("ApartmentInteractions");

                    b.Navigation("ApartmentOwnerApartments");

                    b.Navigation("ApartmentProjectProviders")
                        .IsRequired();

                    b.Navigation("Appointments");

                    b.Navigation("CustomerAppointments");

                    b.Navigation("DepositCancels");

                    b.Navigation("Deposits");

                    b.Navigation("Feedbacks");

                    b.Navigation("Notifications");

                    b.Navigation("ProjectApartments");

                    b.Navigation("ProjectProviderAppointments");

                    b.Navigation("RequestApartments");

                    b.Navigation("StaffAppointments");

                    b.Navigation("VRExperiences");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentProjectProvider", b =>
                {
                    b.Navigation("AgreementUpdateRequests");

                    b.Navigation("ProjectApartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Deposit", b =>
                {
                    b.Navigation("DepositCancels");

                    b.Navigation("Transactions")
                        .IsRequired();
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositCancelType", b =>
                {
                    b.Navigation("DepositCancels");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Facilities", b =>
                {
                    b.Navigation("ApartmentFacilities");
                });

            modelBuilder.Entity("AVR.Domain.Entities.NotificationType", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Slot", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.VRExperience", b =>
                {
                    b.Navigation("VR_Access_Logs");
                });

            modelBuilder.Entity("Apartment", b =>
                {
                    b.Navigation("ApartmentFacilities");

                    b.Navigation("ApartmentImages");

                    b.Navigation("ApartmentInteractions");

                    b.Navigation("ApartmentOwnerApartments");

                    b.Navigation("Appointments");

                    b.Navigation("Deposits");

                    b.Navigation("RequestApartments");

                    b.Navigation("VRExperiences");
                });

            modelBuilder.Entity("ProjectApartment", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("ProjectAccessLogs");

                    b.Navigation("ProjectImages");
                });
#pragma warning restore 612, 618
        }
    }
}
