// <auto-generated />
using System;
using AVR.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AVR.Infrastructure.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241016051751_fixApartmentv4")]
    partial class fixApartmentv4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AVR.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmailConfirmationOtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("OtpExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cd1131e8-2699-4599-a824-1140dd09d512"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            Avatar = "",
                            ConcurrencyStamp = "fc0c23c9-ba30-4f71-9701-0099f74791c8",
                            Email = "quansongngu13@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Quan",
                            NormalizedEmail = "QUANSONGNGU13@GMAIL.COM",
                            NormalizedUserName = "QUANSONGNGU13@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBdQzGHBjtjW3NF0Nb+KnO2T4Uv1OnIJq3W6yDMaRk48LgJJE4lge9rV9tT8QnfuNA==",
                            PhoneNumber = "0949035672",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "69c329bd-52df-4439-ad63-3c3c8b34d00c",
                            TwoFactorEnabled = false,
                            UserName = "quansongngu13@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("4139e5a6-aa80-4ab7-b729-10e3b67a4b64"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            ConcurrencyStamp = "b9c069e8-bddc-433c-b816-bcf30aedd3d9",
                            Email = "johndoe@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "John Doe",
                            NormalizedEmail = "JOHNDOE@EXAMPLE.COM",
                            NormalizedUserName = "JOHNDOE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBDyEC7xbCO8zD8cY0LczqMoSnMNzjD1RpuuCP7r5DIQtMrsHa9/+aG8O2b3oTJqqA==",
                            PhoneNumber = "123456789",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "353e9d32-c4e4-40d2-b9a5-23d49bc398ef",
                            TwoFactorEnabled = false,
                            UserName = "johndoe@example.com"
                        },
                        new
                        {
                            Id = new Guid("c5a60b81-4c14-4bb1-8750-804d7c2c8f42"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            Avatar = "",
                            ConcurrencyStamp = "802f9687-7ba0-4d2e-86d5-c8699eb75f64",
                            Email = "michael.smith@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Michael Smith",
                            NormalizedEmail = "MICHAEL.SMITH@EXAMPLE.COM",
                            NormalizedUserName = "MICHAEL.SMITH@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENWxFvc5bm6g/E3SL+GbMH6W3FLJfu85wWRIJC19qt5WKggdVBHpwVt2JsDgEQGGUg==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1a32874f-e318-4b23-9f9e-068c02bcb9e0",
                            TwoFactorEnabled = false,
                            UserName = "michael.smith@example.com"
                        },
                        new
                        {
                            Id = new Guid("03a35819-2c89-4da1-b52f-cd08bb26632c"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            Avatar = "",
                            ConcurrencyStamp = "0e452659-3306-4dfa-895e-7ea230f7df73",
                            Email = "luong.a11.dbk@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Duc Luong",
                            NormalizedEmail = "LUONG.A11.DBK@GMAIL.COM",
                            NormalizedUserName = "LUONG.A11.DBK@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPEA5o2OZLHFuZJis0giUxg3R3hQoFCVhb36EqfeBD12nUs5d+t4R0CQpvddjIlljg==",
                            PhoneNumber = "0987654321",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "307c408d-5f20-468c-aa83-8cc79439bb8f",
                            TwoFactorEnabled = false,
                            UserName = "luong.a11.dbk@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("1254f6cf-1b42-49f9-b0a0-0fc00e70fb98"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            Avatar = "",
                            ConcurrencyStamp = "770d1c30-b705-4147-9104-3492f1a99ccf",
                            Email = "david.brown@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "David Brown",
                            NormalizedEmail = "DAVID.BROWN@EXAMPLE.COM",
                            NormalizedUserName = "DAVID.BROWN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFiucsTedRmvWdHoH2CT8m8YV8Th6XyQOimvirEKnwBR2E3mGyv/4Y0sZGWOqAivgw==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "a1e1466e-a3cc-4755-88d8-e1c9701638ba",
                            TwoFactorEnabled = false,
                            UserName = "david.brown@example.com"
                        },
                        new
                        {
                            Id = new Guid("76e7138a-9b41-40cf-b291-2b6309346c40"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            Avatar = "",
                            ConcurrencyStamp = "089ce74a-95d4-4f29-9a44-7974ab1d9136",
                            Email = "construction.corp@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Construction Corp",
                            NormalizedEmail = "CONSTRUCTION.CORP@EXAMPLE.COM",
                            NormalizedUserName = "CONSTRUCTION.CORP@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEId+qPqlASwFBO9LfOHJ1eNoQIwMX6HE7ZJvxMDp5VrXKRV0yhousBYP0yl2SvjSDA==",
                            PhoneNumber = "0987654321",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "32319a8d-37f7-4cc1-a024-3b9d36761ae3",
                            TwoFactorEnabled = false,
                            UserName = "construction.corp@example.com"
                        },
                        new
                        {
                            Id = new Guid("347718d9-4999-4228-abf0-e1997a8b0f1c"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            ConcurrencyStamp = "838d4984-1688-437c-88ea-9b621d13801d",
                            Email = "alice.smith@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Alice Smith",
                            NormalizedEmail = "ALICE.SMITH@EXAMPLE.COM",
                            NormalizedUserName = "ALICE.SMITH@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIykAqsSAd9O3glixQfMDYwfiPgRUF7RsaSX5+Ulfi0iOZf56nU0OcfBcHxa/FkvFQ==",
                            PhoneNumber = "0901234567",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "9125f527-b972-4460-811e-d25292dd42cb",
                            TwoFactorEnabled = false,
                            UserName = "alice.smith@example.com"
                        },
                        new
                        {
                            Id = new Guid("9c355129-aca9-4431-80d0-c5af5542219e"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            ConcurrencyStamp = "c3096163-4d5b-4317-88ae-4b08ca07f4d3",
                            Email = "bob.johnson@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Bob Johnson",
                            NormalizedEmail = "BOB.JOHNSON@EXAMPLE.COM",
                            NormalizedUserName = "BOB.JOHNSON@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDq0rpuJMspMd8SP/HWW3RlLhaD7k+blIYnAG6UWOOjmjxS8tciw6WUVSOKsOAm0RA==",
                            PhoneNumber = "0902345678",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "adbac19c-01f0-4b6a-ad5b-bd6df3946cc4",
                            TwoFactorEnabled = false,
                            UserName = "bob.johnson@example.com"
                        },
                        new
                        {
                            Id = new Guid("4cb264ec-7d0f-460c-9752-7cfc8daea97e"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            ConcurrencyStamp = "7bfc1fc6-1f02-4a38-bae9-88996cb646bf",
                            Email = "charlie.brown@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Charlie Brown",
                            NormalizedEmail = "CHARLIE.BROWN@EXAMPLE.COM",
                            NormalizedUserName = "CHARLIE.BROWN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG2Xa172wTrvD1TGsh2or6VQVhey4H3HN7bcZgaTv4nt9ywtUEYQlVyeRwoBSy0ddw==",
                            PhoneNumber = "0903456789",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "8aa50fcb-08c8-447a-a4a1-dbd71468ec82",
                            TwoFactorEnabled = false,
                            UserName = "charlie.brown@example.com"
                        },
                        new
                        {
                            Id = new Guid("16862768-c0a5-4360-a0db-8d736d1b3c51"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            ConcurrencyStamp = "8abec38b-a0a3-487e-8891-2800e1cc9636",
                            Email = "diana.prince@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Diana Prince",
                            NormalizedEmail = "DIANA.PRINCE@EXAMPLE.COM",
                            NormalizedUserName = "DIANA.PRINCE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAED2JaVdldjblCwYd9Fd4RN5hqNan54JtmSl9qXVwRoqBoyWaeFMpXXvtJjJpwilO1w==",
                            PhoneNumber = "0904567890",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1bd1b3c1-8ab1-446a-97c0-01fbec182bcd",
                            TwoFactorEnabled = false,
                            UserName = "diana.prince@example.com"
                        },
                        new
                        {
                            Id = new Guid("c430addd-3ab8-4d82-a292-fa606b6d6b07"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            ConcurrencyStamp = "e4169fc9-35c5-4143-96e1-a863960d4bf4",
                            Email = "eve.adams@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Eve Adams",
                            NormalizedEmail = "EVE.ADAMS@EXAMPLE.COM",
                            NormalizedUserName = "EVE.ADAMS@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENQGgUyatZHpL7ufJFMCdH4qDUnwsHgTCnQl78DqWNKHD+yxVPizpDTfc2N/8KSGGQ==",
                            PhoneNumber = "0905678901",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "92f08e3a-8382-424d-8640-1b584ad8f319",
                            TwoFactorEnabled = false,
                            UserName = "eve.adams@example.com"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.AccountRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("983c15bc-e7d8-41c0-b875-bffb87e5b095"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("3a5122be-2720-4cd2-825f-40671b614447"),
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = new Guid("5d2468bb-5b8d-4318-854f-ba5bfc093259"),
                            Name = "Apartment Owner",
                            NormalizedName = "APARTMENT OWNER"
                        },
                        new
                        {
                            Id = new Guid("876bd4a0-7eda-44d6-8d08-1d2cb9d748f0"),
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        },
                        new
                        {
                            Id = new Guid("03c54f06-4619-4e5c-b9d6-d03d976e5b9c"),
                            Name = "Management",
                            NormalizedName = "MANAGEMENT"
                        },
                        new
                        {
                            Id = new Guid("d98ee50f-8ae2-4f85-913f-4ce482eec305"),
                            Name = "Project Provider",
                            NormalizedName = "PROJECT PROVIDER"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.AgreementUpdateRequest", b =>
                {
                    b.Property<Guid>("AgreementUpdateRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentProjectProviderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RequestDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RequestDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AgreementUpdateRequestID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ApartmentProjectProviderID");

                    b.ToTable("AgreementUpdateRequests");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentFacility", b =>
                {
                    b.Property<Guid>("ApartmentFacilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacilityID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApartmentFacilityID");

                    b.HasIndex("ApartmentID");

                    b.HasIndex("FacilityID");

                    b.ToTable("ApartmentFacilitys");

                    b.HasData(
                        new
                        {
                            ApartmentFacilityID = new Guid("fb079f5d-8237-41cf-9792-8f64d182ca18"),
                            ApartmentID = new Guid("25739b1a-7ea7-4f61-a74f-5ec25d190f88"),
                            FacilityID = new Guid("7da8570b-6910-4040-bbe2-9efd7599667d")
                        },
                        new
                        {
                            ApartmentFacilityID = new Guid("a7c32e22-c8d1-4200-b721-1f0ca5d4dc86"),
                            ApartmentID = new Guid("7d66d7aa-6f25-4d40-91a0-d935a54d5215"),
                            FacilityID = new Guid("1dc04591-d84a-4d60-9458-95a77b649729")
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentImage", b =>
                {
                    b.Property<Guid>("ApartmentImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ApartmentImageID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("ApartmentImages");

                    b.HasData(
                        new
                        {
                            ApartmentImageID = new Guid("4fe22094-b047-4105-b886-5af7c698cef6"),
                            ApartmentID = new Guid("25739b1a-7ea7-4f61-a74f-5ec25d190f88"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7583), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Living Room View",
                            ImageUrl = "https://example.com/apartment1-livingroom.jpg",
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7584), new TimeSpan(0, 7, 0, 0, 0))
                        },
                        new
                        {
                            ApartmentImageID = new Guid("240c1ee2-aa6d-4b47-a84f-837c64d7da81"),
                            ApartmentID = new Guid("25739b1a-7ea7-4f61-a74f-5ec25d190f88"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7587), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bedroom View",
                            ImageUrl = "https://example.com/apartment1-bedroom.jpg",
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7588), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentInteraction", b =>
                {
                    b.Property<Guid>("ApartmentInteractionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("InteractionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("InteractionTypes")
                        .HasColumnType("int");

                    b.HasKey("ApartmentInteractionID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("ApartmentInteractions");

                    b.HasData(
                        new
                        {
                            ApartmentInteractionID = new Guid("55bba41c-e7d1-43c3-830f-a03ea0825e84"),
                            AccountID = new Guid("347718d9-4999-4228-abf0-e1997a8b0f1c"),
                            ApartmentID = new Guid("25739b1a-7ea7-4f61-a74f-5ec25d190f88"),
                            InteractionDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9097), new TimeSpan(0, 7, 0, 0, 0)),
                            InteractionTypes = 0
                        },
                        new
                        {
                            ApartmentInteractionID = new Guid("a2b60397-78b4-4954-bc93-6fb60baadd2a"),
                            AccountID = new Guid("9c355129-aca9-4431-80d0-c5af5542219e"),
                            ApartmentID = new Guid("7d66d7aa-6f25-4d40-91a0-d935a54d5215"),
                            InteractionDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9131), new TimeSpan(0, 7, 0, 0, 0)),
                            InteractionTypes = 1
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentOwnerApartment", b =>
                {
                    b.Property<Guid>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocumentID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("ApartmentOwnerApartment");

                    b.HasData(
                        new
                        {
                            DocumentID = new Guid("9f67396c-a8e9-4203-8a37-60d32045359b"),
                            AccountID = new Guid("1254f6cf-1b42-49f9-b0a0-0fc00e70fb98"),
                            ApartmentID = new Guid("25739b1a-7ea7-4f61-a74f-5ec25d190f88")
                        },
                        new
                        {
                            DocumentID = new Guid("2c3519ec-a6e2-484b-93c3-8f88bad367a1"),
                            AccountID = new Guid("1254f6cf-1b42-49f9-b0a0-0fc00e70fb98"),
                            ApartmentID = new Guid("25739b1a-7ea7-4f61-a74f-5ec25d190f88")
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentProjectProvider", b =>
                {
                    b.Property<Guid>("ApartmentProjectProviderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApartmentProjectDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApartmentProjectProviderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DiagramUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegallInfor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ApartmentProjectProviderID");

                    b.HasIndex("AccountID")
                        .IsUnique();

                    b.ToTable("ApartmentProjectProvider");

                    b.HasData(
                        new
                        {
                            ApartmentProjectProviderID = new Guid("e23bc340-f1b2-48c7-9483-ea89bf470123"),
                            AccountID = new Guid("76e7138a-9b41-40cf-b291-2b6309346c40"),
                            ApartmentProjectDescription = "A provider of luxury high-end apartments.",
                            ApartmentProjectProviderName = "High-End Apartment Provider",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7072), new TimeSpan(0, 7, 0, 0, 0)),
                            DiagramUrl = "https://example.com/diagram.png",
                            LegallInfor = "Legal Information",
                            Location = "City Center",
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7073), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApartmentOwnerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AppointmentDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("AppointmentStatus")
                        .HasColumnType("int");

                    b.Property<int>("AppointmentTypes")
                        .HasColumnType("int");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("AssignedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProjectProviderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SlotID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaffID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AppointmentID");

                    b.HasIndex("ApartmentID");

                    b.HasIndex("ApartmentOwnerID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ProjectProviderID");

                    b.HasIndex("SlotID");

                    b.HasIndex("StaffID");

                    b.ToTable("Appointment");

                    b.HasData(
                        new
                        {
                            AppointmentID = new Guid("9e581a15-367e-4ea1-9ceb-b8bd66e3a797"),
                            ApartmentID = new Guid("25739b1a-7ea7-4f61-a74f-5ec25d190f88"),
                            ApartmentOwnerID = new Guid("1254f6cf-1b42-49f9-b0a0-0fc00e70fb98"),
                            AppointmentDate = new DateTimeOffset(new DateTime(2024, 10, 17, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9347), new TimeSpan(0, 7, 0, 0, 0)),
                            AppointmentStatus = 1,
                            AppointmentTypes = 1,
                            AssignedBy = "Admin",
                            AssignedDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9344), new TimeSpan(0, 7, 0, 0, 0)),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9341), new TimeSpan(0, 7, 0, 0, 0)),
                            CustomerID = new Guid("c430addd-3ab8-4d82-a292-fa606b6d6b07"),
                            Description = "Schedule a viewing for the Skyline Apartment.",
                            ProjectProviderID = new Guid("76e7138a-9b41-40cf-b291-2b6309346c40"),
                            SlotID = new Guid("e7bd0bf8-25da-4c59-8f74-58fc6de9428d"),
                            StaffID = new Guid("4139e5a6-aa80-4ab7-b729-10e3b67a4b64"),
                            Title = "Viewing Appointment for Skyline Apartment",
                            UpdatedDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9343), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.Deposit", b =>
                {
                    b.Property<Guid>("DepositID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DepositStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("constractNumber")
                        .HasColumnType("float");

                    b.Property<double>("depositAmount")
                        .HasColumnType("float");

                    b.Property<double>("depositPercentage")
                        .HasColumnType("float");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("expiryDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepositID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("DepositRequest");

                    b.HasData(
                        new
                        {
                            DepositID = new Guid("53a0a06a-7839-444e-b97f-dd5923e7ada1"),
                            AccountID = new Guid("4cb264ec-7d0f-460c-9752-7cfc8daea97e"),
                            ApartmentID = new Guid("25739b1a-7ea7-4f61-a74f-5ec25d190f88"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9455), new TimeSpan(0, 7, 0, 0, 0)),
                            DepositStatus = 0,
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9465), new TimeSpan(0, 7, 0, 0, 0)),
                            constractNumber = 12345.0,
                            depositAmount = 50000.0,
                            depositPercentage = 20.0,
                            description = "Deposit for Skyline Apartment.",
                            expiryDate = new DateTimeOffset(new DateTime(2024, 11, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9469), new TimeSpan(0, 7, 0, 0, 0)),
                            note = "Initial deposit for apartment"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositCancel", b =>
                {
                    b.Property<Guid>("DepositCancelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CancelDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DepositCancelTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepositID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecoveryPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("RefundDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("updateAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("DepositCancelID");

                    b.HasIndex("AccountID");

                    b.HasIndex("DepositCancelTypeID");

                    b.HasIndex("DepositID");

                    b.ToTable("DepositCancel");

                    b.HasData(
                        new
                        {
                            DepositCancelID = new Guid("fa651074-d6d1-416a-b026-01a70602cd31"),
                            AccountID = new Guid("03a35819-2c89-4da1-b52f-cd08bb26632c"),
                            CancelDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9624), new TimeSpan(0, 7, 0, 0, 0)),
                            DepositCancelTypeID = new Guid("b61c49ae-252f-446b-acf7-d264ffe54b3c"),
                            DepositID = new Guid("53a0a06a-7839-444e-b97f-dd5923e7ada1"),
                            RecoveryPrice = "45000",
                            RefundDate = new DateTimeOffset(new DateTime(2024, 10, 21, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9625), new TimeSpan(0, 7, 0, 0, 0)),
                            updateAt = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9629), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositCancelType", b =>
                {
                    b.Property<Guid>("DepositCancelTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DepositCancelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("DepositCancelTypeID");

                    b.ToTable("DepositCancelTypes");

                    b.HasData(
                        new
                        {
                            DepositCancelTypeID = new Guid("b61c49ae-252f-446b-acf7-d264ffe54b3c"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9412), new TimeSpan(0, 7, 0, 0, 0)),
                            DepositCancelName = "Customer Request",
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9413), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.Facilities", b =>
                {
                    b.Property<Guid>("FacilitiesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacilitiesDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilitiesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FacilitiesID");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            FacilitiesID = new Guid("7da8570b-6910-4040-bbe2-9efd7599667d"),
                            FacilitiesDescription = "A large outdoor swimming pool.",
                            FacilitiesName = "Swimming Pool"
                        },
                        new
                        {
                            FacilitiesID = new Guid("1dc04591-d84a-4d60-9458-95a77b649729"),
                            FacilitiesDescription = "A fully equipped fitness gym.",
                            FacilitiesName = "Gym"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeedbackStatus")
                        .HasColumnType("int");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeedbackID");

                    b.HasIndex("AccountID");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            FeedbackID = new Guid("9ea4b80f-b1b4-447d-8175-56979818888a"),
                            AccountID = new Guid("347718d9-4999-4228-abf0-e1997a8b0f1c"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9692), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "I really enjoyed the experience. Highly recommend!",
                            FeedbackStatus = 0,
                            Rating = 5f,
                            Title = "Great Service!"
                        },
                        new
                        {
                            FeedbackID = new Guid("bf0ac04e-6859-42a0-8f5f-8f277fbf10df"),
                            AccountID = new Guid("9c355129-aca9-4431-80d0-c5af5542219e"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9698), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "The service was okay, but there's room for improvement.",
                            FeedbackStatus = 0,
                            Rating = 3.5f,
                            Title = "Could be better"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("NotificationStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("NotificationTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReferenceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("NotificationID");

                    b.HasIndex("AccountID");

                    b.HasIndex("NotificationTypeID");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            NotificationID = new Guid("6be968dd-ae23-4553-9828-d3147b78dc9f"),
                            AccountID = new Guid("4cb264ec-7d0f-460c-9752-7cfc8daea97e"),
                            Created = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9993), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Thank you for joining us! We hope you enjoy your experience.",
                            IsRead = false,
                            NotificationStatus = 0,
                            NotificationTypeID = new Guid("f1c13d9d-c2d4-4e96-b710-d9b15019c0e0"),
                            ReferenceID = new Guid("94e4e54c-61d5-4ede-a038-74d267f6f3f1"),
                            Title = "Welcome to Our Service",
                            Updated = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9996), new TimeSpan(0, 7, 0, 0, 0))
                        },
                        new
                        {
                            NotificationID = new Guid("a512726f-72fb-4b96-8f8f-87591f6ffc34"),
                            AccountID = new Guid("9c355129-aca9-4431-80d0-c5af5542219e"),
                            Created = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 632, DateTimeKind.Unspecified).AddTicks(11), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Check out our new feature that enhances your experience!",
                            IsRead = false,
                            NotificationStatus = 0,
                            NotificationTypeID = new Guid("f1c13d9d-c2d4-4e96-b710-d9b15019c0e0"),
                            ReferenceID = new Guid("b58ca3ec-1823-4974-8c53-9656dc880e0a"),
                            Title = "New Feature Available",
                            Updated = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 632, DateTimeKind.Unspecified).AddTicks(12), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.NotificationType", b =>
                {
                    b.Property<Guid>("NotificationTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NotificationTypeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationTypeID");

                    b.ToTable("NotificationTypes");

                    b.HasData(
                        new
                        {
                            NotificationTypeID = new Guid("f1c13d9d-c2d4-4e96-b710-d9b15019c0e0"),
                            NotificationTypeDescription = "General notifications for users.",
                            NotificationTypeName = "General"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectAccessLog", b =>
                {
                    b.Property<Guid>("ProjectAccessLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("accessDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ProjectAccessLogID");

                    b.HasIndex("ProjectApartmentID");

                    b.ToTable("ProjectAccessLogs");

                    b.HasData(
                        new
                        {
                            ProjectAccessLogID = new Guid("17702548-1900-487e-a41d-cd8baaa67df9"),
                            ProjectApartmentID = new Guid("0ec34e30-e467-47fb-b8bb-1d650b98c8c8"),
                            accessDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7267), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectImage", b =>
                {
                    b.Property<Guid>("ProjectImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectImageID");

                    b.HasIndex("ProjectApartmentID");

                    b.ToTable("ProjectImages");

                    b.HasData(
                        new
                        {
                            ProjectImageID = new Guid("25ec51ca-b494-4a3b-a2d2-655733306a55"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7298), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Image of the luxury apartment",
                            Name = "Luxury Apartment Image",
                            ProjectApartmentID = new Guid("0ec34e30-e467-47fb-b8bb-1d650b98c8c8"),
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7300), new TimeSpan(0, 7, 0, 0, 0)),
                            Url = "https://example.com/luxury-apartment.jpg"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.RequestApartment", b =>
                {
                    b.Property<Guid>("RequestApartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ResponseDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ResponseMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestApartmentID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("RequestApartments");

                    b.HasData(
                        new
                        {
                            RequestApartmentID = new Guid("90b62055-5bbb-4396-a2fc-878929dafa56"),
                            AccountID = new Guid("9c355129-aca9-4431-80d0-c5af5542219e"),
                            ApartmentID = new Guid("25739b1a-7ea7-4f61-a74f-5ec25d190f88"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9208), new TimeSpan(0, 7, 0, 0, 0)),
                            Note = "Please respond as soon as possible.",
                            RequestMessage = "I would like to know more about this apartment.",
                            ResponseDate = new DateTimeOffset(new DateTime(2024, 10, 17, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9210), new TimeSpan(0, 7, 0, 0, 0)),
                            ResponseMessage = "Your request has been received."
                        },
                        new
                        {
                            RequestApartmentID = new Guid("08a27172-9070-4111-806b-b9468d734901"),
                            AccountID = new Guid("347718d9-4999-4228-abf0-e1997a8b0f1c"),
                            ApartmentID = new Guid("7d66d7aa-6f25-4d40-91a0-d935a54d5215"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9234), new TimeSpan(0, 7, 0, 0, 0)),
                            Note = "Looking forward to your response.",
                            RequestMessage = "Is this apartment still available for booking?",
                            ResponseDate = new DateTimeOffset(new DateTime(2024, 10, 17, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9236), new TimeSpan(0, 7, 0, 0, 0)),
                            ResponseMessage = "The apartment is still available."
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.Slot", b =>
                {
                    b.Property<Guid>("SlotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SlotID");

                    b.ToTable("Slots");

                    b.HasData(
                        new
                        {
                            SlotID = new Guid("e7bd0bf8-25da-4c59-8f74-58fc6de9428d"),
                            EndTime = "10:00 AM",
                            StartTime = "09:00 AM"
                        },
                        new
                        {
                            SlotID = new Guid("c0293b1e-e0f7-4bfa-8b77-baac564874aa"),
                            EndTime = "11:00 AM",
                            StartTime = "10:00 AM"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DepositID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PaymentMethods")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TransactionStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("ammount")
                        .HasColumnType("float");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionID");

                    b.HasIndex("DepositID")
                        .IsUnique();

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionID = new Guid("82d0e010-325f-4f9f-ac31-b8f0d0ed86e2"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9573), new TimeSpan(0, 7, 0, 0, 0)),
                            DepositID = new Guid("53a0a06a-7839-444e-b97f-dd5923e7ada1"),
                            PaymentMethods = 0,
                            TransactionDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9577), new TimeSpan(0, 7, 0, 0, 0)),
                            TransactionStatus = 0,
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(9576), new TimeSpan(0, 7, 0, 0, 0)),
                            ammount = 50000.0,
                            description = "Payment for initial deposit.",
                            note = "Deposit payment"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.VRExperience", b =>
                {
                    b.Property<Guid>("VRExperienceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("video_url_file")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VRExperienceID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("VRExperiences");

                    b.HasData(
                        new
                        {
                            VRExperienceID = new Guid("ce00596d-7890-44b0-b4a0-58d7d7138663"),
                            AccountID = new Guid("4139e5a6-aa80-4ab7-b729-10e3b67a4b64"),
                            ApartmentID = new Guid("25739b1a-7ea7-4f61-a74f-5ec25d190f88"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7638), new TimeSpan(0, 7, 0, 0, 0)),
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7647), new TimeSpan(0, 7, 0, 0, 0)),
                            video_url_file = "https://example.com/vr-experience1.mp4"
                        },
                        new
                        {
                            VRExperienceID = new Guid("4c8274d3-b31e-4308-bab9-203a09e42f49"),
                            AccountID = new Guid("4139e5a6-aa80-4ab7-b729-10e3b67a4b64"),
                            ApartmentID = new Guid("7d66d7aa-6f25-4d40-91a0-d935a54d5215"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7669), new TimeSpan(0, 7, 0, 0, 0)),
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7670), new TimeSpan(0, 7, 0, 0, 0)),
                            video_url_file = "https://example.com/vr-experience2.mp4"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.VR_Access_Log", b =>
                {
                    b.Property<Guid>("VR_Access_LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("VRExperienceID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VR_Access_LogID");

                    b.HasIndex("VRExperienceID");

                    b.ToTable("VR_Access_Logs");

                    b.HasData(
                        new
                        {
                            VR_Access_LogID = new Guid("d50e2cbc-fc36-497f-987f-ad356071e0a6"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7699), new TimeSpan(0, 7, 0, 0, 0)),
                            VRExperienceID = new Guid("ce00596d-7890-44b0-b4a0-58d7d7138663")
                        },
                        new
                        {
                            VR_Access_LogID = new Guid("b46d2cec-0202-43ab-8f51-efc48a6b2540"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7703), new TimeSpan(0, 7, 0, 0, 0)),
                            VRExperienceID = new Guid("4c8274d3-b31e-4308-bab9-203a09e42f49")
                        });
                });

            modelBuilder.Entity("Apartment", b =>
                {
                    b.Property<Guid>("ApartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApartmentStatus")
                        .HasColumnType("int");

                    b.Property<int>("ApartmentType")
                        .HasColumnType("int");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("BalconyDirection")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ExpiryDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfBathrooms")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfRooms")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerSquareMeter")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("ProjectApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RecommendedPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ApartmentID");

                    b.HasIndex("ProjectApartmentID");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            ApartmentID = new Guid("25739b1a-7ea7-4f61-a74f-5ec25d190f88"),
                            Address = "123 Skyline Road, New City",
                            ApartmentName = "Skyline Apartment",
                            ApartmentStatus = 0,
                            ApartmentType = 1,
                            Area = 150.00m,
                            BalconyDirection = 5,
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7329), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "A modern apartment with a skyline view.",
                            Direction = 1,
                            ExpiryDate = new DateTimeOffset(new DateTime(2029, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7341), new TimeSpan(0, 7, 0, 0, 0)),
                            Location = "City Center",
                            NumberOfBathrooms = 2,
                            NumberOfRooms = 3,
                            PricePerSquareMeter = 70000000m,
                            ProjectApartmentID = new Guid("0ec34e30-e467-47fb-b8bb-1d650b98c8c8"),
                            RecommendedPrice = 10000000000m,
                            UpdatedDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7330), new TimeSpan(0, 7, 0, 0, 0))
                        },
                        new
                        {
                            ApartmentID = new Guid("7d66d7aa-6f25-4d40-91a0-d935a54d5215"),
                            Address = "456 Ocean Drive, Coastal City",
                            ApartmentName = "Ocean View Apartment",
                            ApartmentStatus = 2,
                            ApartmentType = 2,
                            Area = 170.00m,
                            BalconyDirection = 8,
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7452), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "A luxurious apartment with an ocean view.",
                            Direction = 2,
                            ExpiryDate = new DateTimeOffset(new DateTime(2027, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7456), new TimeSpan(0, 7, 0, 0, 0)),
                            Location = "Beachfront",
                            NumberOfBathrooms = 3,
                            NumberOfRooms = 4,
                            PricePerSquareMeter = 90000000m,
                            ProjectApartmentID = new Guid("0ec34e30-e467-47fb-b8bb-1d650b98c8c8"),
                            RecommendedPrice = 15000000000m,
                            UpdatedDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7453), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("cd1131e8-2699-4599-a824-1140dd09d512"),
                            RoleId = new Guid("983c15bc-e7d8-41c0-b875-bffb87e5b095")
                        },
                        new
                        {
                            UserId = new Guid("c5a60b81-4c14-4bb1-8750-804d7c2c8f42"),
                            RoleId = new Guid("3a5122be-2720-4cd2-825f-40671b614447")
                        },
                        new
                        {
                            UserId = new Guid("1254f6cf-1b42-49f9-b0a0-0fc00e70fb98"),
                            RoleId = new Guid("5d2468bb-5b8d-4318-854f-ba5bfc093259")
                        },
                        new
                        {
                            UserId = new Guid("4139e5a6-aa80-4ab7-b729-10e3b67a4b64"),
                            RoleId = new Guid("876bd4a0-7eda-44d6-8d08-1d2cb9d748f0")
                        },
                        new
                        {
                            UserId = new Guid("03a35819-2c89-4da1-b52f-cd08bb26632c"),
                            RoleId = new Guid("03c54f06-4619-4e5c-b9d6-d03d976e5b9c")
                        },
                        new
                        {
                            UserId = new Guid("76e7138a-9b41-40cf-b291-2b6309346c40"),
                            RoleId = new Guid("d98ee50f-8ae2-4f85-913f-4ce482eec305")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectApartment", b =>
                {
                    b.Property<Guid>("ProjectApartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentProjectProviderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Price_range")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectApartmentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectApartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectApartmentStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ProjectApartmentID");

                    b.HasIndex("AccountId");

                    b.HasIndex("ApartmentProjectProviderID");

                    b.ToTable("ProjectApartments");

                    b.HasData(
                        new
                        {
                            ProjectApartmentID = new Guid("0ec34e30-e467-47fb-b8bb-1d650b98c8c8"),
                            ApartmentProjectProviderID = new Guid("e23bc340-f1b2-48c7-9483-ea89bf470123"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7124), new TimeSpan(0, 7, 0, 0, 0)),
                            Price_range = "500,000 - 1,000,000 USD",
                            ProjectApartmentDescription = "A spacious luxury apartment with modern amenities.",
                            ProjectApartmentName = "Luxury Apartment",
                            ProjectApartmentStatus = 0,
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 12, 17, 49, 631, DateTimeKind.Unspecified).AddTicks(7125), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.AgreementUpdateRequest", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("AgreementUpdateRequests")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.ApartmentProjectProvider", "ApartmentProjectProvider")
                        .WithMany("AgreementUpdateRequests")
                        .HasForeignKey("ApartmentProjectProviderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("ApartmentProjectProvider");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentFacility", b =>
                {
                    b.HasOne("Apartment", "Apartment")
                        .WithMany("ApartmentFacilities")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Facilities", "Facility")
                        .WithMany("ApartmentFacilities")
                        .HasForeignKey("FacilityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentImage", b =>
                {
                    b.HasOne("Apartment", "Apartments")
                        .WithMany("ApartmentImages")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentInteraction", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("ApartmentInteractions")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apartment", "Apartments")
                        .WithMany("ApartmentInteractions")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentOwnerApartment", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Account")
                        .WithMany("ApartmentOwnerApartments")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apartment", "Apartment")
                        .WithMany("ApartmentOwnerApartments")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentProjectProvider", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithOne("ApartmentProjectProviders")
                        .HasForeignKey("AVR.Domain.Entities.ApartmentProjectProvider", "AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Apartment", "Apartments")
                        .WithMany("Appointments")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Account", "ApartmentOwner")
                        .WithMany("Appointments")
                        .HasForeignKey("ApartmentOwnerID");

                    b.HasOne("AVR.Domain.Entities.Account", "Customer")
                        .WithMany("CustomerAppointments")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AVR.Domain.Entities.Account", "ProjectProvider")
                        .WithMany("ProjectProviderAppointments")
                        .HasForeignKey("ProjectProviderID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AVR.Domain.Entities.Slot", "Slots")
                        .WithMany("Appointments")
                        .HasForeignKey("SlotID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Account", "Staff")
                        .WithMany("StaffAppointments")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApartmentOwner");

                    b.Navigation("Apartments");

                    b.Navigation("Customer");

                    b.Navigation("ProjectProvider");

                    b.Navigation("Slots");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Deposit", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("Deposits")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apartment", "Apartments")
                        .WithMany("Deposits")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositCancel", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("DepositCancels")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.DepositCancelType", "DepositCancelTypes")
                        .WithMany("DepositCancels")
                        .HasForeignKey("DepositCancelTypeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Deposit", "Deposits")
                        .WithMany("DepositCancels")
                        .HasForeignKey("DepositID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("DepositCancelTypes");

                    b.Navigation("Deposits");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("Feedbacks")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Notification", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.NotificationType", "NotificationTypes")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("NotificationTypes");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectAccessLog", b =>
                {
                    b.HasOne("ProjectApartment", "ProjectApartments")
                        .WithMany("ProjectAccessLogs")
                        .HasForeignKey("ProjectApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProjectApartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectImage", b =>
                {
                    b.HasOne("ProjectApartment", "ProjectApartments")
                        .WithMany("ProjectImages")
                        .HasForeignKey("ProjectApartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectApartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.RequestApartment", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("RequestApartments")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apartment", "Apartments")
                        .WithMany("RequestApartments")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Deposit", "Deposits")
                        .WithOne("Transactions")
                        .HasForeignKey("AVR.Domain.Entities.Transaction", "DepositID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deposits");
                });

            modelBuilder.Entity("AVR.Domain.Entities.VRExperience", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("VRExperiences")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apartment", "Apartments")
                        .WithMany("VRExperiences")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.VR_Access_Log", b =>
                {
                    b.HasOne("AVR.Domain.Entities.VRExperience", "VRExperiences")
                        .WithMany("VR_Access_Logs")
                        .HasForeignKey("VRExperienceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("VRExperiences");
                });

            modelBuilder.Entity("Apartment", b =>
                {
                    b.HasOne("ProjectApartment", "ProjectApartment")
                        .WithMany("Apartments")
                        .HasForeignKey("ProjectApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProjectApartment");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.AccountRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.AccountRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectApartment", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany("ProjectApartments")
                        .HasForeignKey("AccountId");

                    b.HasOne("AVR.Domain.Entities.ApartmentProjectProvider", "ApartmentProjectProvider")
                        .WithMany("ProjectApartments")
                        .HasForeignKey("ApartmentProjectProviderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApartmentProjectProvider");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Account", b =>
                {
                    b.Navigation("AgreementUpdateRequests");

                    b.Navigation("ApartmentInteractions");

                    b.Navigation("ApartmentOwnerApartments");

                    b.Navigation("ApartmentProjectProviders")
                        .IsRequired();

                    b.Navigation("Appointments");

                    b.Navigation("CustomerAppointments");

                    b.Navigation("DepositCancels");

                    b.Navigation("Deposits");

                    b.Navigation("Feedbacks");

                    b.Navigation("Notifications");

                    b.Navigation("ProjectApartments");

                    b.Navigation("ProjectProviderAppointments");

                    b.Navigation("RequestApartments");

                    b.Navigation("StaffAppointments");

                    b.Navigation("VRExperiences");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentProjectProvider", b =>
                {
                    b.Navigation("AgreementUpdateRequests");

                    b.Navigation("ProjectApartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Deposit", b =>
                {
                    b.Navigation("DepositCancels");

                    b.Navigation("Transactions")
                        .IsRequired();
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositCancelType", b =>
                {
                    b.Navigation("DepositCancels");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Facilities", b =>
                {
                    b.Navigation("ApartmentFacilities");
                });

            modelBuilder.Entity("AVR.Domain.Entities.NotificationType", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Slot", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.VRExperience", b =>
                {
                    b.Navigation("VR_Access_Logs");
                });

            modelBuilder.Entity("Apartment", b =>
                {
                    b.Navigation("ApartmentFacilities");

                    b.Navigation("ApartmentImages");

                    b.Navigation("ApartmentInteractions");

                    b.Navigation("ApartmentOwnerApartments");

                    b.Navigation("Appointments");

                    b.Navigation("Deposits");

                    b.Navigation("RequestApartments");

                    b.Navigation("VRExperiences");
                });

            modelBuilder.Entity("ProjectApartment", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("ProjectAccessLogs");

                    b.Navigation("ProjectImages");
                });
#pragma warning restore 612, 618
        }
    }
}
