// <auto-generated />
using System;
using AVR.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AVR.Infrastructure.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241016041248_fixApartmentv3")]
    partial class fixApartmentv3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AVR.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmailConfirmationOtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("OtpExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1de769f5-986a-4158-a05f-ee82ee3607de"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            Avatar = "",
                            ConcurrencyStamp = "cad362ae-8cd8-4fba-8e83-5aa4da17bebc",
                            Email = "quansongngu13@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Quan",
                            NormalizedEmail = "QUANSONGNGU13@GMAIL.COM",
                            NormalizedUserName = "QUANSONGNGU13@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAE2R2XcS0cx+wCOcOruGQMgbyLjP5mDwWt4d+r8sLHglzjldkQgYtK4+NTOV6VkOg==",
                            PhoneNumber = "0949035672",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "9dd163e0-3166-41b8-88fd-113a9b8fa4d2",
                            TwoFactorEnabled = false,
                            UserName = "quansongngu13@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("4a0f911f-d62f-4b36-8903-ecab22af2040"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            ConcurrencyStamp = "4107601a-8817-404a-aeef-4fc946f9f967",
                            Email = "johndoe@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "John Doe",
                            NormalizedEmail = "JOHNDOE@EXAMPLE.COM",
                            NormalizedUserName = "JOHNDOE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMdtVXOgikByf1PbeF+cZD4q7etsBrEdBg4+I6/vi5hPmq0jP5tpxmIajcLxi1yaxw==",
                            PhoneNumber = "123456789",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "755fb2c0-62f2-4ebb-995f-889dfe51a8dd",
                            TwoFactorEnabled = false,
                            UserName = "johndoe@example.com"
                        },
                        new
                        {
                            Id = new Guid("abcda63f-3c2a-45f8-90ab-659b5e863d82"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            Avatar = "",
                            ConcurrencyStamp = "ac2a25be-f355-4e47-b24e-3712dec2a65e",
                            Email = "michael.smith@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Michael Smith",
                            NormalizedEmail = "MICHAEL.SMITH@EXAMPLE.COM",
                            NormalizedUserName = "MICHAEL.SMITH@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAOKutWtPLEBx5o53yABmo98FpAU2bkowLVYDo1ttCgVD+fAiUEIuVgFuPAZr1+v4A==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "f2908942-2894-4008-87b8-015beb1dbd4f",
                            TwoFactorEnabled = false,
                            UserName = "michael.smith@example.com"
                        },
                        new
                        {
                            Id = new Guid("4d2b3c33-8cf9-473c-b427-f3c0f291c407"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            Avatar = "",
                            ConcurrencyStamp = "d2c65c68-6404-4aae-aa07-4e0bfcb3c094",
                            Email = "luong.a11.dbk@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Duc Luong",
                            NormalizedEmail = "LUONG.A11.DBK@GMAIL.COM",
                            NormalizedUserName = "LUONG.A11.DBK@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO7UBAmebJQCV2Dr5tFYxl9dPPBb09uFEF0hLwrGZTVOgSh/5xbN5MqclkuXYexoWQ==",
                            PhoneNumber = "0987654321",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "71a687e8-f2c7-4bbf-9455-34edc42a2023",
                            TwoFactorEnabled = false,
                            UserName = "luong.a11.dbk@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("6741ea0a-ca09-4c8d-ba34-d5b7f7eb738d"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            Avatar = "",
                            ConcurrencyStamp = "419ec0f9-d3c1-4013-aa94-eb1f0e5981a9",
                            Email = "david.brown@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "David Brown",
                            NormalizedEmail = "DAVID.BROWN@EXAMPLE.COM",
                            NormalizedUserName = "DAVID.BROWN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAFtL5638g095wAbnJJeWXt06pxPM0eSv7yu0FdD9M+fGUVZrWm9JRgdQ22hqjt79A==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "c8d590e7-44e9-4da4-b94e-61b9952088eb",
                            TwoFactorEnabled = false,
                            UserName = "david.brown@example.com"
                        },
                        new
                        {
                            Id = new Guid("23ec4579-ae03-4f2b-aa48-19bf88ba5d2a"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            Avatar = "",
                            ConcurrencyStamp = "2281279f-e340-40fc-82ad-bbf1f40894d2",
                            Email = "construction.corp@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Construction Corp",
                            NormalizedEmail = "CONSTRUCTION.CORP@EXAMPLE.COM",
                            NormalizedUserName = "CONSTRUCTION.CORP@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECP5Q0ciSNZ1OMGE4cie12pZ+CXu53SrtmMV4ibKV+UghHNS6PbzcZ5udy6fcijD7A==",
                            PhoneNumber = "0987654321",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "0e296256-c5b4-4c5e-aa0a-40b979b5f51a",
                            TwoFactorEnabled = false,
                            UserName = "construction.corp@example.com"
                        },
                        new
                        {
                            Id = new Guid("3a0e9663-d0ed-441e-91f8-2e0e32033bfe"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            ConcurrencyStamp = "e20768cd-1de4-4732-9778-eaa6dcb9d329",
                            Email = "alice.smith@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Alice Smith",
                            NormalizedEmail = "ALICE.SMITH@EXAMPLE.COM",
                            NormalizedUserName = "ALICE.SMITH@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELNio8c38Fn5NIynMh5lIbIqN28KpKmWJtjXdmXPmV4HwTpbfTTZMvSVxd+lmxq77g==",
                            PhoneNumber = "0901234567",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "ed78b3d5-5f56-4c2f-960f-56904c9dacb3",
                            TwoFactorEnabled = false,
                            UserName = "alice.smith@example.com"
                        },
                        new
                        {
                            Id = new Guid("d586ba3e-ce95-4d39-89c4-553ac4b08fe8"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            ConcurrencyStamp = "20e3d0fc-3123-48b8-9959-07c7beae14f6",
                            Email = "bob.johnson@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Bob Johnson",
                            NormalizedEmail = "BOB.JOHNSON@EXAMPLE.COM",
                            NormalizedUserName = "BOB.JOHNSON@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGv5+vP9Ey7lz0iIIZvrT/aDwtps5OmEuJyLu6vbxfgo9SgBCKI3g4/1VJQet34cRA==",
                            PhoneNumber = "0902345678",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "a97a683b-1a5e-41f5-9775-2df34ef20806",
                            TwoFactorEnabled = false,
                            UserName = "bob.johnson@example.com"
                        },
                        new
                        {
                            Id = new Guid("0aad200d-282d-414f-8b97-e4244d01d425"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            ConcurrencyStamp = "25a48eae-efb0-46a7-95a5-3cf2c9f7608d",
                            Email = "charlie.brown@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Charlie Brown",
                            NormalizedEmail = "CHARLIE.BROWN@EXAMPLE.COM",
                            NormalizedUserName = "CHARLIE.BROWN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFRvEk0KUioLf2NSvMIhHaZ3f6Pmk2J00JuHgV0sBoSqH85rhK39AiXW1JAf/5pFDw==",
                            PhoneNumber = "0903456789",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "29de081c-64e4-40f9-87ea-1bc9524d080d",
                            TwoFactorEnabled = false,
                            UserName = "charlie.brown@example.com"
                        },
                        new
                        {
                            Id = new Guid("92181cd3-6cc8-4d35-8f74-cb5b2de4ed8c"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            ConcurrencyStamp = "4e063b9b-8a5a-4d49-8cb4-657299e2d3cf",
                            Email = "diana.prince@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Diana Prince",
                            NormalizedEmail = "DIANA.PRINCE@EXAMPLE.COM",
                            NormalizedUserName = "DIANA.PRINCE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEL2ePM2UdKOCJbbdQKLL+YwuFlok316NYPIgnBrvoC5e7pHqoDu7Q3B23F5dhiyzbQ==",
                            PhoneNumber = "0904567890",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "b1a0aeae-716c-4305-860d-57367ec38088",
                            TwoFactorEnabled = false,
                            UserName = "diana.prince@example.com"
                        },
                        new
                        {
                            Id = new Guid("104d6b4e-afbc-4a44-b907-d31d16325afa"),
                            AccessFailedCount = 0,
                            AccountStatus = 0,
                            ConcurrencyStamp = "02e5d98f-d880-42e6-a947-346795be658e",
                            Email = "eve.adams@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Eve Adams",
                            NormalizedEmail = "EVE.ADAMS@EXAMPLE.COM",
                            NormalizedUserName = "EVE.ADAMS@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFp5qRJhe5/LXvuCbfjvscF2qEtcpkWfQ6ctryOE38360NsFT727D3Pi9z2sgKOrnA==",
                            PhoneNumber = "0905678901",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "5d0bcc6f-60fe-4470-bbd2-b3fca43a6603",
                            TwoFactorEnabled = false,
                            UserName = "eve.adams@example.com"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.AccountRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("750f1b1b-391f-4350-9213-8d800fbb52ca"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("ae847f98-a394-4dae-9125-0cf73b34428a"),
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = new Guid("fa82bb09-cb8e-4f8e-ab1e-f06125ec2b1b"),
                            Name = "Apartment Owner",
                            NormalizedName = "APARTMENT OWNER"
                        },
                        new
                        {
                            Id = new Guid("e70a8d79-567b-4e14-920f-f066f100d1c3"),
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        },
                        new
                        {
                            Id = new Guid("1974beca-b455-4000-82d0-3d62477b9746"),
                            Name = "Management",
                            NormalizedName = "MANAGEMENT"
                        },
                        new
                        {
                            Id = new Guid("af01b0c9-50b7-429e-a34e-24e5d21fda70"),
                            Name = "Project Provider",
                            NormalizedName = "PROJECT PROVIDER"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.AgreementUpdateRequest", b =>
                {
                    b.Property<Guid>("AgreementUpdateRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentProjectProviderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RequestDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RequestDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AgreementUpdateRequestID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ApartmentProjectProviderID");

                    b.ToTable("AgreementUpdateRequests");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentFacility", b =>
                {
                    b.Property<Guid>("ApartmentFacilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacilityID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApartmentFacilityID");

                    b.HasIndex("ApartmentID");

                    b.HasIndex("FacilityID");

                    b.ToTable("ApartmentFacilitys");

                    b.HasData(
                        new
                        {
                            ApartmentFacilityID = new Guid("976f4d7c-8fb9-482e-9f6a-a791f3a95b51"),
                            ApartmentID = new Guid("b5808261-a113-4cb7-b5e6-c2824f4eae65"),
                            FacilityID = new Guid("3fe6daa7-b415-4f7b-8650-eb47cb6bb721")
                        },
                        new
                        {
                            ApartmentFacilityID = new Guid("491fd7c5-785a-47a2-847c-68e9304fb68c"),
                            ApartmentID = new Guid("a2bff192-cf6c-4a22-9b09-ab6e25824f3d"),
                            FacilityID = new Guid("ba796b2e-e802-4859-8165-42e00660a702")
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentImage", b =>
                {
                    b.Property<Guid>("ApartmentImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ApartmentImageID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("ApartmentImages");

                    b.HasData(
                        new
                        {
                            ApartmentImageID = new Guid("e4b41e98-e236-427e-9609-e3e71bf80bc1"),
                            ApartmentID = new Guid("b5808261-a113-4cb7-b5e6-c2824f4eae65"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(4203), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Living Room View",
                            ImageUrl = "https://example.com/apartment1-livingroom.jpg",
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(4205), new TimeSpan(0, 7, 0, 0, 0))
                        },
                        new
                        {
                            ApartmentImageID = new Guid("03eb4876-daa2-412a-b96b-2c26f09f41e5"),
                            ApartmentID = new Guid("b5808261-a113-4cb7-b5e6-c2824f4eae65"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(4208), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Bedroom View",
                            ImageUrl = "https://example.com/apartment1-bedroom.jpg",
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(4209), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentInteraction", b =>
                {
                    b.Property<Guid>("ApartmentInteractionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("InteractionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("InteractionTypes")
                        .HasColumnType("int");

                    b.HasKey("ApartmentInteractionID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("ApartmentInteractions");

                    b.HasData(
                        new
                        {
                            ApartmentInteractionID = new Guid("48fea201-92ea-4df8-86f5-cc155723b9e5"),
                            AccountID = new Guid("3a0e9663-d0ed-441e-91f8-2e0e32033bfe"),
                            ApartmentID = new Guid("b5808261-a113-4cb7-b5e6-c2824f4eae65"),
                            InteractionDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5162), new TimeSpan(0, 7, 0, 0, 0)),
                            InteractionTypes = 0
                        },
                        new
                        {
                            ApartmentInteractionID = new Guid("52038528-1f87-4d88-9dc1-267a14874899"),
                            AccountID = new Guid("d586ba3e-ce95-4d39-89c4-553ac4b08fe8"),
                            ApartmentID = new Guid("a2bff192-cf6c-4a22-9b09-ab6e25824f3d"),
                            InteractionDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5168), new TimeSpan(0, 7, 0, 0, 0)),
                            InteractionTypes = 1
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentOwnerApartment", b =>
                {
                    b.Property<Guid>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocumentID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("ApartmentOwnerApartment");

                    b.HasData(
                        new
                        {
                            DocumentID = new Guid("ac36dde2-5015-41ef-b187-cc0ea795016c"),
                            AccountID = new Guid("6741ea0a-ca09-4c8d-ba34-d5b7f7eb738d"),
                            ApartmentID = new Guid("b5808261-a113-4cb7-b5e6-c2824f4eae65")
                        },
                        new
                        {
                            DocumentID = new Guid("84cf57bb-a54c-4f37-9f3f-3e75894fcf6a"),
                            AccountID = new Guid("6741ea0a-ca09-4c8d-ba34-d5b7f7eb738d"),
                            ApartmentID = new Guid("b5808261-a113-4cb7-b5e6-c2824f4eae65")
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentProjectProvider", b =>
                {
                    b.Property<Guid>("ApartmentProjectProviderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApartmentProjectDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApartmentProjectProviderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DiagramUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegallInfor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ApartmentProjectProviderID");

                    b.HasIndex("AccountID")
                        .IsUnique();

                    b.ToTable("ApartmentProjectProvider");

                    b.HasData(
                        new
                        {
                            ApartmentProjectProviderID = new Guid("8618b741-5505-4fe4-bd9c-39c8853bddef"),
                            AccountID = new Guid("23ec4579-ae03-4f2b-aa48-19bf88ba5d2a"),
                            ApartmentProjectDescription = "A provider of luxury high-end apartments.",
                            ApartmentProjectProviderName = "High-End Apartment Provider",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(3777), new TimeSpan(0, 7, 0, 0, 0)),
                            DiagramUrl = "https://example.com/diagram.png",
                            LegallInfor = "Legal Information",
                            Location = "City Center",
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(3778), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApartmentOwnerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AppointmentDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("AppointmentStatus")
                        .HasColumnType("int");

                    b.Property<int>("AppointmentTypes")
                        .HasColumnType("int");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("AssignedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProjectProviderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SlotID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaffID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AppointmentID");

                    b.HasIndex("ApartmentID");

                    b.HasIndex("ApartmentOwnerID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ProjectProviderID");

                    b.HasIndex("SlotID");

                    b.HasIndex("StaffID");

                    b.ToTable("Appointment");

                    b.HasData(
                        new
                        {
                            AppointmentID = new Guid("5fbb8986-1a3c-4d22-8b38-7c6b5ca4d67a"),
                            ApartmentID = new Guid("b5808261-a113-4cb7-b5e6-c2824f4eae65"),
                            ApartmentOwnerID = new Guid("6741ea0a-ca09-4c8d-ba34-d5b7f7eb738d"),
                            AppointmentDate = new DateTimeOffset(new DateTime(2024, 10, 17, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5272), new TimeSpan(0, 7, 0, 0, 0)),
                            AppointmentStatus = 1,
                            AppointmentTypes = 1,
                            AssignedBy = "Admin",
                            AssignedDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5271), new TimeSpan(0, 7, 0, 0, 0)),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5269), new TimeSpan(0, 7, 0, 0, 0)),
                            CustomerID = new Guid("104d6b4e-afbc-4a44-b907-d31d16325afa"),
                            Description = "Schedule a viewing for the Skyline Apartment.",
                            ProjectProviderID = new Guid("23ec4579-ae03-4f2b-aa48-19bf88ba5d2a"),
                            SlotID = new Guid("de8cd175-5fa8-4935-a8a9-9629db85b6c2"),
                            StaffID = new Guid("4a0f911f-d62f-4b36-8903-ecab22af2040"),
                            Title = "Viewing Appointment for Skyline Apartment",
                            UpdatedDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5270), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.Deposit", b =>
                {
                    b.Property<Guid>("DepositID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DepositStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("constractNumber")
                        .HasColumnType("float");

                    b.Property<double>("depositAmount")
                        .HasColumnType("float");

                    b.Property<double>("depositPercentage")
                        .HasColumnType("float");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("expiryDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepositID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("DepositRequest");

                    b.HasData(
                        new
                        {
                            DepositID = new Guid("3450eb59-1c9e-4307-b769-a8b45297bb53"),
                            AccountID = new Guid("0aad200d-282d-414f-8b97-e4244d01d425"),
                            ApartmentID = new Guid("b5808261-a113-4cb7-b5e6-c2824f4eae65"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5328), new TimeSpan(0, 7, 0, 0, 0)),
                            DepositStatus = 0,
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5332), new TimeSpan(0, 7, 0, 0, 0)),
                            constractNumber = 12345.0,
                            depositAmount = 50000.0,
                            depositPercentage = 20.0,
                            description = "Deposit for Skyline Apartment.",
                            expiryDate = new DateTimeOffset(new DateTime(2024, 11, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5333), new TimeSpan(0, 7, 0, 0, 0)),
                            note = "Initial deposit for apartment"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositCancel", b =>
                {
                    b.Property<Guid>("DepositCancelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CancelDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DepositCancelTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepositID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecoveryPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("RefundDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("updateAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("DepositCancelID");

                    b.HasIndex("AccountID");

                    b.HasIndex("DepositCancelTypeID");

                    b.HasIndex("DepositID");

                    b.ToTable("DepositCancel");

                    b.HasData(
                        new
                        {
                            DepositCancelID = new Guid("5f1fcd4e-7e44-40be-9920-5cf21055e33e"),
                            AccountID = new Guid("4d2b3c33-8cf9-473c-b427-f3c0f291c407"),
                            CancelDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5407), new TimeSpan(0, 7, 0, 0, 0)),
                            DepositCancelTypeID = new Guid("ec79ebcf-5ba5-4ede-b744-230594513ace"),
                            DepositID = new Guid("3450eb59-1c9e-4307-b769-a8b45297bb53"),
                            RecoveryPrice = "45000",
                            RefundDate = new DateTimeOffset(new DateTime(2024, 10, 21, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5408), new TimeSpan(0, 7, 0, 0, 0)),
                            updateAt = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5409), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositCancelType", b =>
                {
                    b.Property<Guid>("DepositCancelTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DepositCancelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("DepositCancelTypeID");

                    b.ToTable("DepositCancelTypes");

                    b.HasData(
                        new
                        {
                            DepositCancelTypeID = new Guid("ec79ebcf-5ba5-4ede-b744-230594513ace"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5304), new TimeSpan(0, 7, 0, 0, 0)),
                            DepositCancelName = "Customer Request",
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5305), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.Facilities", b =>
                {
                    b.Property<Guid>("FacilitiesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacilitiesDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilitiesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FacilitiesID");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            FacilitiesID = new Guid("3fe6daa7-b415-4f7b-8650-eb47cb6bb721"),
                            FacilitiesDescription = "A large outdoor swimming pool.",
                            FacilitiesName = "Swimming Pool"
                        },
                        new
                        {
                            FacilitiesID = new Guid("ba796b2e-e802-4859-8165-42e00660a702"),
                            FacilitiesDescription = "A fully equipped fitness gym.",
                            FacilitiesName = "Gym"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeedbackStatus")
                        .HasColumnType("int");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeedbackID");

                    b.HasIndex("AccountID");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            FeedbackID = new Guid("6e82b502-40d9-499c-9d85-dc45b8e4c9d5"),
                            AccountID = new Guid("3a0e9663-d0ed-441e-91f8-2e0e32033bfe"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5435), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "I really enjoyed the experience. Highly recommend!",
                            FeedbackStatus = 0,
                            Rating = 5f,
                            Title = "Great Service!"
                        },
                        new
                        {
                            FeedbackID = new Guid("a223e6e6-6eb8-44d6-b32d-8dfd1a709138"),
                            AccountID = new Guid("d586ba3e-ce95-4d39-89c4-553ac4b08fe8"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5440), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "The service was okay, but there's room for improvement.",
                            FeedbackStatus = 0,
                            Rating = 3.5f,
                            Title = "Could be better"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("NotificationStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("NotificationTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReferenceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("NotificationID");

                    b.HasIndex("AccountID");

                    b.HasIndex("NotificationTypeID");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            NotificationID = new Guid("19f0542a-9bc7-4d76-8c69-e77839b1103f"),
                            AccountID = new Guid("0aad200d-282d-414f-8b97-e4244d01d425"),
                            Created = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5493), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Thank you for joining us! We hope you enjoy your experience.",
                            IsRead = false,
                            NotificationStatus = 0,
                            NotificationTypeID = new Guid("d9b60fb0-9eb0-4d25-9202-bca8eb92fb2f"),
                            ReferenceID = new Guid("81e8297c-ad41-4fde-8008-4919ba9d4502"),
                            Title = "Welcome to Our Service",
                            Updated = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5493), new TimeSpan(0, 7, 0, 0, 0))
                        },
                        new
                        {
                            NotificationID = new Guid("b5c5fde3-c32c-407e-995b-4888b9fef508"),
                            AccountID = new Guid("d586ba3e-ce95-4d39-89c4-553ac4b08fe8"),
                            Created = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5502), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Check out our new feature that enhances your experience!",
                            IsRead = false,
                            NotificationStatus = 0,
                            NotificationTypeID = new Guid("d9b60fb0-9eb0-4d25-9202-bca8eb92fb2f"),
                            ReferenceID = new Guid("e3420a1b-48d0-4b17-b436-8ff86f8884e2"),
                            Title = "New Feature Available",
                            Updated = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5502), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.NotificationType", b =>
                {
                    b.Property<Guid>("NotificationTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NotificationTypeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationTypeID");

                    b.ToTable("NotificationTypes");

                    b.HasData(
                        new
                        {
                            NotificationTypeID = new Guid("d9b60fb0-9eb0-4d25-9202-bca8eb92fb2f"),
                            NotificationTypeDescription = "General notifications for users.",
                            NotificationTypeName = "General"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectAccessLog", b =>
                {
                    b.Property<Guid>("ProjectAccessLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("accessDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ProjectAccessLogID");

                    b.HasIndex("ProjectApartmentID");

                    b.ToTable("ProjectAccessLogs");

                    b.HasData(
                        new
                        {
                            ProjectAccessLogID = new Guid("a57c10b8-1a87-457d-a4f7-9f6c0a864959"),
                            ProjectApartmentID = new Guid("189f216f-c675-4170-977f-373054c1c272"),
                            accessDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(3918), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectApartmentApartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentID");

                    b.HasIndex("ProjectApartmentID");

                    b.ToTable("ProjectApartmentApartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectImage", b =>
                {
                    b.Property<Guid>("ProjectImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectImageID");

                    b.HasIndex("ProjectApartmentID");

                    b.ToTable("ProjectImages");

                    b.HasData(
                        new
                        {
                            ProjectImageID = new Guid("41f1cccd-a777-4dc5-b468-54cbbf22d511"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(3951), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "Image of the luxury apartment",
                            Name = "Luxury Apartment Image",
                            ProjectApartmentID = new Guid("189f216f-c675-4170-977f-373054c1c272"),
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(3952), new TimeSpan(0, 7, 0, 0, 0)),
                            Url = "https://example.com/luxury-apartment.jpg"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.RequestApartment", b =>
                {
                    b.Property<Guid>("RequestApartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ResponseDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ResponseMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestApartmentID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("RequestApartments");

                    b.HasData(
                        new
                        {
                            RequestApartmentID = new Guid("8c8af83f-5a61-480d-96b4-f8a64fd5202d"),
                            AccountID = new Guid("d586ba3e-ce95-4d39-89c4-553ac4b08fe8"),
                            ApartmentID = new Guid("b5808261-a113-4cb7-b5e6-c2824f4eae65"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5199), new TimeSpan(0, 7, 0, 0, 0)),
                            Note = "Please respond as soon as possible.",
                            RequestMessage = "I would like to know more about this apartment.",
                            ResponseDate = new DateTimeOffset(new DateTime(2024, 10, 17, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5200), new TimeSpan(0, 7, 0, 0, 0)),
                            ResponseMessage = "Your request has been received."
                        },
                        new
                        {
                            RequestApartmentID = new Guid("9efa29ba-18a3-4a93-947a-641895da9d99"),
                            AccountID = new Guid("3a0e9663-d0ed-441e-91f8-2e0e32033bfe"),
                            ApartmentID = new Guid("a2bff192-cf6c-4a22-9b09-ab6e25824f3d"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5209), new TimeSpan(0, 7, 0, 0, 0)),
                            Note = "Looking forward to your response.",
                            RequestMessage = "Is this apartment still available for booking?",
                            ResponseDate = new DateTimeOffset(new DateTime(2024, 10, 17, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5210), new TimeSpan(0, 7, 0, 0, 0)),
                            ResponseMessage = "The apartment is still available."
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.Slot", b =>
                {
                    b.Property<Guid>("SlotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SlotID");

                    b.ToTable("Slots");

                    b.HasData(
                        new
                        {
                            SlotID = new Guid("de8cd175-5fa8-4935-a8a9-9629db85b6c2"),
                            EndTime = "10:00 AM",
                            StartTime = "09:00 AM"
                        },
                        new
                        {
                            SlotID = new Guid("029ff706-b97f-4350-a58a-068da85537d1"),
                            EndTime = "11:00 AM",
                            StartTime = "10:00 AM"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DepositID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PaymentMethods")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TransactionStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("ammount")
                        .HasColumnType("float");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionID");

                    b.HasIndex("DepositID")
                        .IsUnique();

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionID = new Guid("15bc1b77-ed91-42f9-b23b-278c0575a0f3"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5379), new TimeSpan(0, 7, 0, 0, 0)),
                            DepositID = new Guid("3450eb59-1c9e-4307-b769-a8b45297bb53"),
                            PaymentMethods = 0,
                            TransactionDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5382), new TimeSpan(0, 7, 0, 0, 0)),
                            TransactionStatus = 0,
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5381), new TimeSpan(0, 7, 0, 0, 0)),
                            ammount = 50000.0,
                            description = "Payment for initial deposit.",
                            note = "Deposit payment"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.VRExperience", b =>
                {
                    b.Property<Guid>("VRExperienceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("video_url_file")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VRExperienceID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("VRExperiences");

                    b.HasData(
                        new
                        {
                            VRExperienceID = new Guid("eeba5701-7abf-4e63-9715-1e7f10d7f002"),
                            AccountID = new Guid("4a0f911f-d62f-4b36-8903-ecab22af2040"),
                            ApartmentID = new Guid("b5808261-a113-4cb7-b5e6-c2824f4eae65"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(4249), new TimeSpan(0, 7, 0, 0, 0)),
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(4255), new TimeSpan(0, 7, 0, 0, 0)),
                            video_url_file = "https://example.com/vr-experience1.mp4"
                        },
                        new
                        {
                            VRExperienceID = new Guid("b0ca0860-ffe5-45dd-ab22-36b0f48abda4"),
                            AccountID = new Guid("4a0f911f-d62f-4b36-8903-ecab22af2040"),
                            ApartmentID = new Guid("a2bff192-cf6c-4a22-9b09-ab6e25824f3d"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5033), new TimeSpan(0, 7, 0, 0, 0)),
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5034), new TimeSpan(0, 7, 0, 0, 0)),
                            video_url_file = "https://example.com/vr-experience2.mp4"
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.VR_Access_Log", b =>
                {
                    b.Property<Guid>("VR_Access_LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("VRExperienceID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VR_Access_LogID");

                    b.HasIndex("VRExperienceID");

                    b.ToTable("VR_Access_Logs");

                    b.HasData(
                        new
                        {
                            VR_Access_LogID = new Guid("8e46f4ed-4ddd-436a-919e-29a7aebc247f"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5126), new TimeSpan(0, 7, 0, 0, 0)),
                            VRExperienceID = new Guid("eeba5701-7abf-4e63-9715-1e7f10d7f002")
                        },
                        new
                        {
                            VR_Access_LogID = new Guid("8e8e3573-56a1-4431-b963-e21b1b12cfaa"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(5130), new TimeSpan(0, 7, 0, 0, 0)),
                            VRExperienceID = new Guid("b0ca0860-ffe5-45dd-ab22-36b0f48abda4")
                        });
                });

            modelBuilder.Entity("Apartment", b =>
                {
                    b.Property<Guid>("ApartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApartmentStatus")
                        .HasColumnType("int");

                    b.Property<int>("ApartmentType")
                        .HasColumnType("int");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("BalconyDirection")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ExpiryDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfBathrooms")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfRooms")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerSquareMeter")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("ProjectApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RecommendedPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ApartmentID");

                    b.HasIndex("ProjectApartmentID");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            ApartmentID = new Guid("b5808261-a113-4cb7-b5e6-c2824f4eae65"),
                            Address = "123 Skyline Road, New City",
                            ApartmentName = "Skyline Apartment",
                            ApartmentStatus = 0,
                            ApartmentType = 1,
                            Area = 150.00m,
                            BalconyDirection = 5,
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(3983), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "A modern apartment with a skyline view.",
                            Direction = 1,
                            ExpiryDate = new DateTimeOffset(new DateTime(2029, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(3994), new TimeSpan(0, 7, 0, 0, 0)),
                            Location = "City Center",
                            NumberOfBathrooms = 2,
                            NumberOfRooms = 3,
                            PricePerSquareMeter = 70000000m,
                            ProjectApartmentID = new Guid("189f216f-c675-4170-977f-373054c1c272"),
                            RecommendedPrice = 10000000000m,
                            UpdatedDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(3984), new TimeSpan(0, 7, 0, 0, 0))
                        },
                        new
                        {
                            ApartmentID = new Guid("a2bff192-cf6c-4a22-9b09-ab6e25824f3d"),
                            Address = "456 Ocean Drive, Coastal City",
                            ApartmentName = "Ocean View Apartment",
                            ApartmentStatus = 2,
                            ApartmentType = 2,
                            Area = 170.00m,
                            BalconyDirection = 8,
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(4009), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "A luxurious apartment with an ocean view.",
                            Direction = 2,
                            ExpiryDate = new DateTimeOffset(new DateTime(2027, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(4012), new TimeSpan(0, 7, 0, 0, 0)),
                            Location = "Beachfront",
                            NumberOfBathrooms = 3,
                            NumberOfRooms = 4,
                            PricePerSquareMeter = 90000000m,
                            ProjectApartmentID = new Guid("189f216f-c675-4170-977f-373054c1c272"),
                            RecommendedPrice = 15000000000m,
                            UpdatedDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(4010), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("1de769f5-986a-4158-a05f-ee82ee3607de"),
                            RoleId = new Guid("750f1b1b-391f-4350-9213-8d800fbb52ca")
                        },
                        new
                        {
                            UserId = new Guid("abcda63f-3c2a-45f8-90ab-659b5e863d82"),
                            RoleId = new Guid("ae847f98-a394-4dae-9125-0cf73b34428a")
                        },
                        new
                        {
                            UserId = new Guid("6741ea0a-ca09-4c8d-ba34-d5b7f7eb738d"),
                            RoleId = new Guid("fa82bb09-cb8e-4f8e-ab1e-f06125ec2b1b")
                        },
                        new
                        {
                            UserId = new Guid("4a0f911f-d62f-4b36-8903-ecab22af2040"),
                            RoleId = new Guid("e70a8d79-567b-4e14-920f-f066f100d1c3")
                        },
                        new
                        {
                            UserId = new Guid("4d2b3c33-8cf9-473c-b427-f3c0f291c407"),
                            RoleId = new Guid("1974beca-b455-4000-82d0-3d62477b9746")
                        },
                        new
                        {
                            UserId = new Guid("23ec4579-ae03-4f2b-aa48-19bf88ba5d2a"),
                            RoleId = new Guid("af01b0c9-50b7-429e-a34e-24e5d21fda70")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectApartment", b =>
                {
                    b.Property<Guid>("ProjectApartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentProjectProviderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Price_range")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectApartmentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectApartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectApartmentStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ProjectApartmentID");

                    b.HasIndex("AccountId");

                    b.HasIndex("ApartmentProjectProviderID");

                    b.ToTable("ProjectApartments");

                    b.HasData(
                        new
                        {
                            ProjectApartmentID = new Guid("189f216f-c675-4170-977f-373054c1c272"),
                            ApartmentProjectProviderID = new Guid("8618b741-5505-4fe4-bd9c-39c8853bddef"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(3822), new TimeSpan(0, 7, 0, 0, 0)),
                            Price_range = "500,000 - 1,000,000 USD",
                            ProjectApartmentDescription = "A spacious luxury apartment with modern amenities.",
                            ProjectApartmentName = "Luxury Apartment",
                            ProjectApartmentStatus = 0,
                            UpdateDate = new DateTimeOffset(new DateTime(2024, 10, 16, 11, 12, 47, 64, DateTimeKind.Unspecified).AddTicks(3823), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AVR.Domain.Entities.AgreementUpdateRequest", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("AgreementUpdateRequests")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.ApartmentProjectProvider", "ApartmentProjectProvider")
                        .WithMany("AgreementUpdateRequests")
                        .HasForeignKey("ApartmentProjectProviderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("ApartmentProjectProvider");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentFacility", b =>
                {
                    b.HasOne("Apartment", "Apartment")
                        .WithMany("ApartmentFacilities")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Facilities", "Facility")
                        .WithMany("ApartmentFacilities")
                        .HasForeignKey("FacilityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentImage", b =>
                {
                    b.HasOne("Apartment", "Apartments")
                        .WithMany("ApartmentImages")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentInteraction", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("ApartmentInteractions")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apartment", "Apartments")
                        .WithMany("ApartmentInteractions")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentOwnerApartment", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Account")
                        .WithMany("ApartmentOwnerApartments")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apartment", "Apartment")
                        .WithMany("ApartmentOwnerApartments")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentProjectProvider", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithOne("ApartmentProjectProviders")
                        .HasForeignKey("AVR.Domain.Entities.ApartmentProjectProvider", "AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Apartment", "Apartments")
                        .WithMany("Appointments")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Account", "ApartmentOwner")
                        .WithMany("Appointments")
                        .HasForeignKey("ApartmentOwnerID");

                    b.HasOne("AVR.Domain.Entities.Account", "Customer")
                        .WithMany("CustomerAppointments")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AVR.Domain.Entities.Account", "ProjectProvider")
                        .WithMany("ProjectProviderAppointments")
                        .HasForeignKey("ProjectProviderID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AVR.Domain.Entities.Slot", "Slots")
                        .WithMany("Appointments")
                        .HasForeignKey("SlotID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Account", "Staff")
                        .WithMany("StaffAppointments")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApartmentOwner");

                    b.Navigation("Apartments");

                    b.Navigation("Customer");

                    b.Navigation("ProjectProvider");

                    b.Navigation("Slots");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Deposit", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("Deposits")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apartment", "Apartments")
                        .WithMany("Deposits")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositCancel", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("DepositCancels")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.DepositCancelType", "DepositCancelTypes")
                        .WithMany("DepositCancels")
                        .HasForeignKey("DepositCancelTypeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Deposit", "Deposits")
                        .WithMany("DepositCancels")
                        .HasForeignKey("DepositID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("DepositCancelTypes");

                    b.Navigation("Deposits");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("Feedbacks")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Notification", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.NotificationType", "NotificationTypes")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("NotificationTypes");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectAccessLog", b =>
                {
                    b.HasOne("ProjectApartment", "ProjectApartments")
                        .WithMany("ProjectAccessLogs")
                        .HasForeignKey("ProjectApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProjectApartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectApartmentApartment", b =>
                {
                    b.HasOne("Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectApartment", "ProjectApartment")
                        .WithMany()
                        .HasForeignKey("ProjectApartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("ProjectApartment");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectImage", b =>
                {
                    b.HasOne("ProjectApartment", "ProjectApartments")
                        .WithMany("ProjectImages")
                        .HasForeignKey("ProjectApartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectApartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.RequestApartment", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("RequestApartments")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apartment", "Apartments")
                        .WithMany("RequestApartments")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Deposit", "Deposits")
                        .WithOne("Transactions")
                        .HasForeignKey("AVR.Domain.Entities.Transaction", "DepositID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deposits");
                });

            modelBuilder.Entity("AVR.Domain.Entities.VRExperience", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("VRExperiences")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apartment", "Apartments")
                        .WithMany("VRExperiences")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.VR_Access_Log", b =>
                {
                    b.HasOne("AVR.Domain.Entities.VRExperience", "VRExperiences")
                        .WithMany("VR_Access_Logs")
                        .HasForeignKey("VRExperienceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("VRExperiences");
                });

            modelBuilder.Entity("Apartment", b =>
                {
                    b.HasOne("ProjectApartment", "ProjectApartment")
                        .WithMany("Apartments")
                        .HasForeignKey("ProjectApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProjectApartment");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.AccountRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.AccountRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectApartment", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany("ProjectApartments")
                        .HasForeignKey("AccountId");

                    b.HasOne("AVR.Domain.Entities.ApartmentProjectProvider", "ApartmentProjectProvider")
                        .WithMany("ProjectApartments")
                        .HasForeignKey("ApartmentProjectProviderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApartmentProjectProvider");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Account", b =>
                {
                    b.Navigation("AgreementUpdateRequests");

                    b.Navigation("ApartmentInteractions");

                    b.Navigation("ApartmentOwnerApartments");

                    b.Navigation("ApartmentProjectProviders")
                        .IsRequired();

                    b.Navigation("Appointments");

                    b.Navigation("CustomerAppointments");

                    b.Navigation("DepositCancels");

                    b.Navigation("Deposits");

                    b.Navigation("Feedbacks");

                    b.Navigation("Notifications");

                    b.Navigation("ProjectApartments");

                    b.Navigation("ProjectProviderAppointments");

                    b.Navigation("RequestApartments");

                    b.Navigation("StaffAppointments");

                    b.Navigation("VRExperiences");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentProjectProvider", b =>
                {
                    b.Navigation("AgreementUpdateRequests");

                    b.Navigation("ProjectApartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Deposit", b =>
                {
                    b.Navigation("DepositCancels");

                    b.Navigation("Transactions")
                        .IsRequired();
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositCancelType", b =>
                {
                    b.Navigation("DepositCancels");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Facilities", b =>
                {
                    b.Navigation("ApartmentFacilities");
                });

            modelBuilder.Entity("AVR.Domain.Entities.NotificationType", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Slot", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.VRExperience", b =>
                {
                    b.Navigation("VR_Access_Logs");
                });

            modelBuilder.Entity("Apartment", b =>
                {
                    b.Navigation("ApartmentFacilities");

                    b.Navigation("ApartmentImages");

                    b.Navigation("ApartmentInteractions");

                    b.Navigation("ApartmentOwnerApartments");

                    b.Navigation("Appointments");

                    b.Navigation("Deposits");

                    b.Navigation("RequestApartments");

                    b.Navigation("VRExperiences");
                });

            modelBuilder.Entity("ProjectApartment", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("ProjectAccessLogs");

                    b.Navigation("ProjectImages");
                });
#pragma warning restore 612, 618
        }
    }
}
