// <auto-generated />
using System;
using AVR.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AVR.Infrastructure.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241113194359_fixDB_v231")]
    partial class fixDB_v23
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AVR.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<int?>("ActiveAssignmentCount")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmailConfirmationOtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("OtpExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AVR.Domain.Entities.AccountRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("AVR.Domain.Entities.AgreementUpdateRequest", b =>
                {
                    b.Property<Guid>("AgreementUpdateRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AgreementUpdateStatus")
                        .HasColumnType("int");

                    b.Property<int>("AgreementUpdateType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("RequestDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RequestDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AgreementUpdateRequestID");

                    b.HasIndex("AccountID");

                    b.ToTable("AgreementUpdateRequests");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentImage", b =>
                {
                    b.Property<Guid>("ApartmentImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ApartmentImageID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("ApartmentImages");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentInteraction", b =>
                {
                    b.Property<Guid>("ApartmentInteractionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("InteractionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("InteractionTypes")
                        .HasColumnType("int");

                    b.HasKey("ApartmentInteractionID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("ApartmentInteractions");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentOwnerApartment", b =>
                {
                    b.Property<Guid>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocumentID");

                    b.HasIndex("AccountID")
                        .IsUnique();

                    b.HasIndex("ApartmentID")
                        .IsUnique();

                    b.ToTable("ApartmentOwnerApartment");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentProjectProvider", b =>
                {
                    b.Property<Guid>("ApartmentProjectProviderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApartmentProjectDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApartmentProjectProviderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DiagramUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegallInfor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ApartmentProjectProviderID");

                    b.HasIndex("AccountID")
                        .IsUnique();

                    b.ToTable("ProjectProvider");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApplicationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("DepositPercentage")
                        .HasColumnType("float");

                    b.Property<int>("ExpiryDurationInMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ApplicationSettings");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AppointmentDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("AppointmentStatus")
                        .HasColumnType("int");

                    b.Property<int>("AppointmentTypes")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("AssignedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AssignedTeamMemberID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SlotID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AppointmentID");

                    b.HasIndex("AccountId");

                    b.HasIndex("ApartmentID");

                    b.HasIndex("AssignedTeamMemberID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("SlotID");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("AVR.Domain.Entities.AppointmentRequest", b =>
                {
                    b.Property<Guid>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AssignedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AssignedTeamMemberID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("PreferredDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<TimeSpan?>("PreferredTime")
                        .HasColumnType("time");

                    b.Property<int>("RequestType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("RequestID");

                    b.HasIndex("ApartmentID");

                    b.HasIndex("AssignedTeamMemberID");

                    b.HasIndex("CustomerID");

                    b.ToTable("AppointmentRequest");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Deposit", b =>
                {
                    b.Property<Guid>("DepositID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DepositStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("depositAmount")
                        .HasColumnType("float");

                    b.Property<double>("depositPercentage")
                        .HasColumnType("float");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("expiryDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("paymentAmount")
                        .HasColumnType("float");

                    b.HasKey("DepositID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("DepositRequest");
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositCancel", b =>
                {
                    b.Property<Guid>("DepositCancelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CancelDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DepositCancelTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepositID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecoveryPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("RefundDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("updateAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("DepositCancelID");

                    b.HasIndex("AccountID");

                    b.HasIndex("DepositCancelTypeID");

                    b.HasIndex("DepositID");

                    b.ToTable("DepositCancel");
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositCancelType", b =>
                {
                    b.Property<Guid>("DepositCancelTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DepositCancelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("DepositCancelTypeID");

                    b.ToTable("DepositCancelTypes");
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositProfile", b =>
                {
                    b.Property<Guid>("ProfileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfIssue")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepositID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityCardBackImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityCardFrontImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfileID");

                    b.HasIndex("DepositID")
                        .IsUnique();

                    b.ToTable("DepositProfile");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Facilities", b =>
                {
                    b.Property<Guid>("FacilitiesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacilitiesDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilitiesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FacilitiesID");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeedbackStatus")
                        .HasColumnType("int");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeedbackID");

                    b.HasIndex("AccountID");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("NotificationTypes")
                        .HasColumnType("int");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationID");

                    b.HasIndex("AccountID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectAccessLog", b =>
                {
                    b.Property<Guid>("ProjectAccessLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("accessDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ProjectAccessLogID");

                    b.HasIndex("ProjectApartmentID");

                    b.ToTable("ProjectAccessLogs");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectFacility", b =>
                {
                    b.Property<Guid>("ProjectFacilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacilityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectApartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProjectFacilityID");

                    b.HasIndex("FacilityID");

                    b.HasIndex("ProjectApartmentId");

                    b.ToTable("ProjectFacilities");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectImage", b =>
                {
                    b.Property<Guid>("ProjectImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectImageID");

                    b.HasIndex("ProjectApartmentID");

                    b.ToTable("ProjectImages");
                });

            modelBuilder.Entity("AVR.Domain.Entities.PropertyRequest", b =>
                {
                    b.Property<Guid>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AssignedTeamMemberID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExpectedPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("OwnerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("RequestDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestID");

                    b.HasIndex("AssignedTeamMemberID");

                    b.HasIndex("OwnerID");

                    b.ToTable("PropertyRequest");
                });

            modelBuilder.Entity("AVR.Domain.Entities.PropertyVerification", b =>
                {
                    b.Property<Guid>("VerificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LegalDocumentsURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("int");

                    b.HasKey("VerificationID");

                    b.HasIndex("ApartmentID")
                        .IsUnique();

                    b.ToTable("PropertyVerification");
                });

            modelBuilder.Entity("AVR.Domain.Entities.RequestApartment", b =>
                {
                    b.Property<Guid>("RequestApartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ResponseDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ResponseMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestApartmentID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("RequestApartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.RequestAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssignedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("AssignedTeamMemberID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompleteDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RequestType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId");

                    b.HasIndex("AssignedTeamMemberID");

                    b.ToTable("RequestAssignment");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Slot", b =>
                {
                    b.Property<Guid>("SlotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SlotID");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeamDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamType")
                        .HasColumnType("int");

                    b.HasKey("TeamID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("AVR.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("TeamMemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TeamMemberID");

                    b.HasIndex("AccountID");

                    b.HasIndex("TeamID");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DepositID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PaymentMethods")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TransactionStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("ammount")
                        .HasColumnType("float");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionID");

                    b.HasIndex("DepositID")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("AVR.Domain.Entities.VRExperience", b =>
                {
                    b.Property<Guid>("VRExperienceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignedTeamMemberID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("video_url_file")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VRExperienceID");

                    b.HasIndex("ApartmentID");

                    b.HasIndex("AssignedTeamMemberID");

                    b.ToTable("VRExperiences");
                });

            modelBuilder.Entity("AVR.Domain.Entities.VR_Access_Log", b =>
                {
                    b.Property<Guid>("VR_Access_LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("VRExperienceID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VR_Access_LogID");

                    b.HasIndex("VRExperienceID");

                    b.ToTable("VR_Access_Logs");
                });

            modelBuilder.Entity("Apartment", b =>
                {
                    b.Property<Guid>("ApartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApartmentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApartmentStatus")
                        .HasColumnType("int");

                    b.Property<int>("ApartmentType")
                        .HasColumnType("int");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid?>("AssignedTeamMemberID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BalconyDirection")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ExpiryDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfBathrooms")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfRooms")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PricePerSquareMeter")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid?>("ProjectApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApartmentID");

                    b.HasIndex("AssignedTeamMemberID");

                    b.HasIndex("ProjectApartmentID");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectApartment", b =>
                {
                    b.Property<Guid>("ProjectApartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApartmentArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ApartmentProjectProviderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ConstructionEndYear")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ConstructionStartYear")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Price_range")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectApartmentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectApartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectApartmentStatus")
                        .HasColumnType("int");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectType")
                        .HasColumnType("int");

                    b.Property<Guid?>("TeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TotalApartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ProjectApartmentID");

                    b.HasIndex("AccountId");

                    b.HasIndex("ApartmentProjectProviderID");

                    b.HasIndex("TeamID");

                    b.ToTable("ProjectApartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.AgreementUpdateRequest", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("AgreementUpdateRequests")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentImage", b =>
                {
                    b.HasOne("Apartment", "Apartments")
                        .WithMany("ApartmentImages")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentInteraction", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("ApartmentInteractions")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apartment", "Apartments")
                        .WithMany("ApartmentInteractions")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentOwnerApartment", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Account")
                        .WithOne("ApartmentOwnerApartment")
                        .HasForeignKey("AVR.Domain.Entities.ApartmentOwnerApartment", "AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apartment", "Apartment")
                        .WithOne("ApartmentOwnerApartment")
                        .HasForeignKey("AVR.Domain.Entities.ApartmentOwnerApartment", "ApartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentProjectProvider", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithOne("ApartmentProjectProviders")
                        .HasForeignKey("AVR.Domain.Entities.ApartmentProjectProvider", "AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany("Appointments")
                        .HasForeignKey("AccountId");

                    b.HasOne("Apartment", "Apartments")
                        .WithMany("Appointments")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.TeamMember", "AssignedTeamMember")
                        .WithMany("Appointments")
                        .HasForeignKey("AssignedTeamMemberID");

                    b.HasOne("AVR.Domain.Entities.Account", "Customer")
                        .WithMany("CustomerAppointments")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Slot", "Slots")
                        .WithMany("Appointments")
                        .HasForeignKey("SlotID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Apartments");

                    b.Navigation("AssignedTeamMember");

                    b.Navigation("Customer");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("AVR.Domain.Entities.AppointmentRequest", b =>
                {
                    b.HasOne("Apartment", "Apartment")
                        .WithMany("AppointmentRequests")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.TeamMember", "AssignedTeamMember")
                        .WithMany("AppointmentRequests")
                        .HasForeignKey("AssignedTeamMemberID");

                    b.HasOne("AVR.Domain.Entities.Account", "Customer")
                        .WithMany("CustomerAppointmentRequests")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("AssignedTeamMember");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Deposit", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("Deposits")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apartment", "Apartments")
                        .WithMany("Deposits")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositCancel", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("DepositCancels")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.DepositCancelType", "DepositCancelTypes")
                        .WithMany("DepositCancels")
                        .HasForeignKey("DepositCancelTypeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Deposit", "Deposits")
                        .WithMany("DepositCancels")
                        .HasForeignKey("DepositID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("DepositCancelTypes");

                    b.Navigation("Deposits");
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositProfile", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Deposit", "Deposit")
                        .WithOne("DepositProfile")
                        .HasForeignKey("AVR.Domain.Entities.DepositProfile", "DepositID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deposit");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("Feedbacks")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Notification", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectAccessLog", b =>
                {
                    b.HasOne("ProjectApartment", "ProjectApartments")
                        .WithMany("ProjectAccessLogs")
                        .HasForeignKey("ProjectApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProjectApartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectFacility", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Facilities", "Facility")
                        .WithMany("ProjectFacilities")
                        .HasForeignKey("FacilityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectApartment", "ProjectApartment")
                        .WithMany("ProjectFacilities")
                        .HasForeignKey("ProjectApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("ProjectApartment");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectImage", b =>
                {
                    b.HasOne("ProjectApartment", "ProjectApartments")
                        .WithMany("ProjectImages")
                        .HasForeignKey("ProjectApartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectApartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.PropertyRequest", b =>
                {
                    b.HasOne("AVR.Domain.Entities.TeamMember", "AssignedTeamMember")
                        .WithMany()
                        .HasForeignKey("AssignedTeamMemberID");

                    b.HasOne("AVR.Domain.Entities.Account", "Owner")
                        .WithMany("OwnedPropertyRequests")
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AssignedTeamMember");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AVR.Domain.Entities.PropertyVerification", b =>
                {
                    b.HasOne("Apartment", "Apartment")
                        .WithOne("PropertyVerification")
                        .HasForeignKey("AVR.Domain.Entities.PropertyVerification", "ApartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("AVR.Domain.Entities.RequestApartment", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("RequestApartments")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apartment", "Apartments")
                        .WithMany("RequestApartments")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.RequestAssignment", b =>
                {
                    b.HasOne("AVR.Domain.Entities.TeamMember", "AssignedTeamMember")
                        .WithMany("RequestAssignments")
                        .HasForeignKey("AssignedTeamMemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTeamMember");
                });

            modelBuilder.Entity("AVR.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Account")
                        .WithMany("TeamMembers")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Deposit", "Deposits")
                        .WithOne("Transactions")
                        .HasForeignKey("AVR.Domain.Entities.Transaction", "DepositID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deposits");
                });

            modelBuilder.Entity("AVR.Domain.Entities.VRExperience", b =>
                {
                    b.HasOne("Apartment", "Apartments")
                        .WithMany("VRExperiences")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.TeamMember", "AssignedTeamMembers")
                        .WithMany("VRExperiences")
                        .HasForeignKey("AssignedTeamMemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartments");

                    b.Navigation("AssignedTeamMembers");
                });

            modelBuilder.Entity("AVR.Domain.Entities.VR_Access_Log", b =>
                {
                    b.HasOne("AVR.Domain.Entities.VRExperience", "VRExperiences")
                        .WithMany("VR_Access_Logs")
                        .HasForeignKey("VRExperienceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("VRExperiences");
                });

            modelBuilder.Entity("Apartment", b =>
                {
                    b.HasOne("AVR.Domain.Entities.TeamMember", "AssignedTeamMember")
                        .WithMany("Apartments")
                        .HasForeignKey("AssignedTeamMemberID");

                    b.HasOne("ProjectApartment", "ProjectApartment")
                        .WithMany("Apartments")
                        .HasForeignKey("ProjectApartmentID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AssignedTeamMember");

                    b.Navigation("ProjectApartment");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.AccountRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.AccountRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectApartment", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany("ProjectApartments")
                        .HasForeignKey("AccountId");

                    b.HasOne("AVR.Domain.Entities.ApartmentProjectProvider", "ApartmentProjectProvider")
                        .WithMany("ProjectApartments")
                        .HasForeignKey("ApartmentProjectProviderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Team", "Team")
                        .WithMany("ProjectApartments")
                        .HasForeignKey("TeamID");

                    b.Navigation("ApartmentProjectProvider");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Account", b =>
                {
                    b.Navigation("AgreementUpdateRequests");

                    b.Navigation("ApartmentInteractions");

                    b.Navigation("ApartmentOwnerApartment")
                        .IsRequired();

                    b.Navigation("ApartmentProjectProviders")
                        .IsRequired();

                    b.Navigation("Appointments");

                    b.Navigation("CustomerAppointmentRequests");

                    b.Navigation("CustomerAppointments");

                    b.Navigation("DepositCancels");

                    b.Navigation("Deposits");

                    b.Navigation("Feedbacks");

                    b.Navigation("Notifications");

                    b.Navigation("OwnedPropertyRequests");

                    b.Navigation("ProjectApartments");

                    b.Navigation("RequestApartments");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentProjectProvider", b =>
                {
                    b.Navigation("ProjectApartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Deposit", b =>
                {
                    b.Navigation("DepositCancels");

                    b.Navigation("DepositProfile")
                        .IsRequired();

                    b.Navigation("Transactions")
                        .IsRequired();
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositCancelType", b =>
                {
                    b.Navigation("DepositCancels");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Facilities", b =>
                {
                    b.Navigation("ProjectFacilities");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Slot", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Team", b =>
                {
                    b.Navigation("ProjectApartments");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("AVR.Domain.Entities.TeamMember", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("AppointmentRequests");

                    b.Navigation("Appointments");

                    b.Navigation("RequestAssignments");

                    b.Navigation("VRExperiences");
                });

            modelBuilder.Entity("AVR.Domain.Entities.VRExperience", b =>
                {
                    b.Navigation("VR_Access_Logs");
                });

            modelBuilder.Entity("Apartment", b =>
                {
                    b.Navigation("ApartmentImages");

                    b.Navigation("ApartmentInteractions");

                    b.Navigation("ApartmentOwnerApartment")
                        .IsRequired();

                    b.Navigation("AppointmentRequests");

                    b.Navigation("Appointments");

                    b.Navigation("Deposits");

                    b.Navigation("PropertyVerification")
                        .IsRequired();

                    b.Navigation("RequestApartments");

                    b.Navigation("VRExperiences");
                });

            modelBuilder.Entity("ProjectApartment", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("ProjectAccessLogs");

                    b.Navigation("ProjectFacilities");

                    b.Navigation("ProjectImages");
                });
#pragma warning restore 612, 618
        }
    }
}
