// <auto-generated />
using System;
using AVR.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AVR.Infrastructure.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AVR.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AVR.Domain.Entities.AccountRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("AVR.Domain.Entities.AgreementUpdateRequest", b =>
                {
                    b.Property<Guid>("AgreementUpdateRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentProjectProviderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManagementID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RequestDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RequestDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AgreementUpdateRequestID");

                    b.HasIndex("ApartmentProjectProviderID");

                    b.HasIndex("ManagementID");

                    b.ToTable("AgreementUpdateRequest");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Apartment", b =>
                {
                    b.Property<Guid>("ApartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentFacilitiesApartmentFacilityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ApartmentOwnerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApartmentStatus")
                        .HasColumnType("int");

                    b.Property<int>("ApartmentType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("expiryDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numberOfRooms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pricePerSquareMeter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("recommendedPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApartmentID");

                    b.HasIndex("ApartmentFacilitiesApartmentFacilityID");

                    b.HasIndex("ApartmentOwnerID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentFacility", b =>
                {
                    b.Property<Guid>("ApartmentFacilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacilityID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApartmentFacilityID");

                    b.ToTable("ApartmentFacility");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentImage", b =>
                {
                    b.Property<Guid>("ApartmentImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ApartmentImageID");

                    b.HasIndex("ApartmentID");

                    b.ToTable("ApartmentImages");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentInteraction", b =>
                {
                    b.Property<Guid>("ApartmentInteractionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("InteractionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("InteractionTypes")
                        .HasColumnType("int");

                    b.HasKey("ApartmentInteractionID");

                    b.HasIndex("ApartmentID");

                    b.HasIndex("CustomerID");

                    b.ToTable("ApartmentInteractions");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentOwner", b =>
                {
                    b.Property<Guid>("ApartmentOwnerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConstructionPermit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LandUserRightCertificate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherDocuments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerShipCertificate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApartmentOwnerID");

                    b.HasIndex("AccountID")
                        .IsUnique();

                    b.ToTable("ApartmentOwners");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentProjectProvider", b =>
                {
                    b.Property<Guid>("ApartmentProjectProviderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApartmentProjectDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApartmentProjectProviderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DiagramUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegallInfor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ApartmentProjectProviderID");

                    b.HasIndex("AccountID")
                        .IsUnique();

                    b.ToTable("ApartmentProjectProvider");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AppointmentDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("AppointmentStatus")
                        .HasColumnType("int");

                    b.Property<int>("AppointmentTypes")
                        .HasColumnType("int");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("AssignedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SlotID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StaffID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AppointmentID");

                    b.HasIndex("ApartmentID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("SlotID");

                    b.HasIndex("StaffID");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.HasIndex("AccountID")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Deposit", b =>
                {
                    b.Property<Guid>("DepositID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DepositStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("constractNumber")
                        .HasColumnType("float");

                    b.Property<double>("depositAmount")
                        .HasColumnType("float");

                    b.Property<double>("depositPercentage")
                        .HasColumnType("float");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("expiryDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepositID");

                    b.HasIndex("ApartmentID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Deposit");
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositCancel", b =>
                {
                    b.Property<Guid>("DepositCancelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CancelDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DepositCancelTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepositID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManagementID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecoveryPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("RefundDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("updateAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("DepositCancelID");

                    b.HasIndex("DepositCancelTypeID");

                    b.HasIndex("DepositID");

                    b.HasIndex("ManagementID");

                    b.ToTable("DepositCancel");
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositCancelType", b =>
                {
                    b.Property<Guid>("DepositCancelTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DepositCancelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("DepositCancelTypeID");

                    b.ToTable("DepositCancelType");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Facilities", b =>
                {
                    b.Property<Guid>("FacilitiesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentFacilitiesApartmentFacilityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacilitiesDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilitiesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FacilitiesID");

                    b.HasIndex("ApartmentFacilitiesApartmentFacilityID");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeedbackStatus")
                        .HasColumnType("int");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeedbackID");

                    b.HasIndex("AccountID");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Management", b =>
                {
                    b.Property<Guid>("ManagementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ManagementEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagementName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagementPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManagementID");

                    b.HasIndex("AccountID")
                        .IsUnique();

                    b.ToTable("Managements");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("NotificationStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("NotificationTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReferenceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("NotificationID");

                    b.HasIndex("AccountID");

                    b.HasIndex("NotificationTypeID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AVR.Domain.Entities.NotificationType", b =>
                {
                    b.Property<Guid>("NotificationTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NotificationTypeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationTypeID");

                    b.ToTable("NotificationTypes");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectAccessLog", b =>
                {
                    b.Property<Guid>("ProjectAccessLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("accessDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ProjectAccessLogID");

                    b.HasIndex("ProjectApartmentID");

                    b.ToTable("ProjectAccessLogs");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectApartment", b =>
                {
                    b.Property<Guid>("ProjectApartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ManagementID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Price_range")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectApartmentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectApartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectApartmentStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectImageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ProjectApartmentID");

                    b.HasIndex("ManagementID");

                    b.HasIndex("ProjectImageID");

                    b.ToTable("ProjectApartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectImage", b =>
                {
                    b.Property<Guid>("ProjectImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectImageID");

                    b.ToTable("ProjectImages");
                });

            modelBuilder.Entity("AVR.Domain.Entities.RequestApartment", b =>
                {
                    b.Property<int>("RequestApartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestApartmentID"));

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManagementID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ResponseDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ResponseMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestApartmentID");

                    b.HasIndex("ApartmentID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ManagementID");

                    b.ToTable("RequestApartment");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Slot", b =>
                {
                    b.Property<Guid>("SlotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SlotID");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Staff", b =>
                {
                    b.Property<Guid>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StaffEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdateAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffID");

                    b.HasIndex("AccountID")
                        .IsUnique();

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DepositID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PaymentMethods")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TransactionStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("ammount")
                        .HasColumnType("float");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionID");

                    b.HasIndex("DepositID")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("AVR.Domain.Entities.VRExperience", b =>
                {
                    b.Property<Guid>("VRExperienceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("StaffID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("video_url_file")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VRExperienceID");

                    b.HasIndex("ApartmentID");

                    b.HasIndex("StaffID");

                    b.ToTable("VRExperiences");
                });

            modelBuilder.Entity("AVR.Domain.Entities.VR_Access_Log", b =>
                {
                    b.Property<Guid>("VR_Access_LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("VRExperienceID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VR_Access_LogID");

                    b.HasIndex("VRExperienceID");

                    b.ToTable("VR_Access_Logs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AVR.Domain.Entities.AgreementUpdateRequest", b =>
                {
                    b.HasOne("AVR.Domain.Entities.ApartmentProjectProvider", "ApartmentProjectProvider")
                        .WithMany("AgreementUpdateRequests")
                        .HasForeignKey("ApartmentProjectProviderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Management", "Management")
                        .WithMany("AgreementUpdateRequests")
                        .HasForeignKey("ManagementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApartmentProjectProvider");

                    b.Navigation("Management");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Apartment", b =>
                {
                    b.HasOne("AVR.Domain.Entities.ApartmentFacility", "ApartmentFacilities")
                        .WithMany("Apartments")
                        .HasForeignKey("ApartmentFacilitiesApartmentFacilityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.ApartmentOwner", "ApartmentOwners")
                        .WithMany("Apartments")
                        .HasForeignKey("ApartmentOwnerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.ProjectApartment", "ProjectApartments")
                        .WithMany("Apartments")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApartmentFacilities");

                    b.Navigation("ApartmentOwners");

                    b.Navigation("ProjectApartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentImage", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Apartment", "Apartments")
                        .WithMany("ApartmentImages")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentInteraction", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Apartment", "Apartments")
                        .WithMany("ApartmentInteractions")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Customer", "Customers")
                        .WithMany("ApartmentInteractions")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Apartments");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentOwner", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithOne("ApartmentOwners")
                        .HasForeignKey("AVR.Domain.Entities.ApartmentOwner", "AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentProjectProvider", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithOne("ApartmentProjectProviders")
                        .HasForeignKey("AVR.Domain.Entities.ApartmentProjectProvider", "AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Apartment", "Apartments")
                        .WithMany("Appointments")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Customer", "Customers")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Slot", "Slots")
                        .WithMany("Appointments")
                        .HasForeignKey("SlotID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Staff", "Staffs")
                        .WithMany("Appointments")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Apartments");

                    b.Navigation("Customers");

                    b.Navigation("Slots");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Customer", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithOne("Customers")
                        .HasForeignKey("AVR.Domain.Entities.Customer", "AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Deposit", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Apartment", "Apartments")
                        .WithMany("Deposits")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Customer", "Customers")
                        .WithMany("Deposits")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Apartments");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositCancel", b =>
                {
                    b.HasOne("AVR.Domain.Entities.DepositCancelType", "DepositCancelTypes")
                        .WithMany("DepositCancels")
                        .HasForeignKey("DepositCancelTypeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Deposit", "Deposits")
                        .WithMany("DepositCancels")
                        .HasForeignKey("DepositID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Management", "Managements")
                        .WithMany("DepositCancels")
                        .HasForeignKey("ManagementID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DepositCancelTypes");

                    b.Navigation("Deposits");

                    b.Navigation("Managements");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Facilities", b =>
                {
                    b.HasOne("AVR.Domain.Entities.ApartmentFacility", "ApartmentFacilities")
                        .WithMany("Facilities")
                        .HasForeignKey("ApartmentFacilitiesApartmentFacilityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApartmentFacilities");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("Feedbacks")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Management", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithOne("Managements")
                        .HasForeignKey("AVR.Domain.Entities.Management", "AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Notification", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.NotificationType", "NotificationTypes")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("NotificationTypes");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectAccessLog", b =>
                {
                    b.HasOne("AVR.Domain.Entities.ProjectApartment", "ProjectApartments")
                        .WithMany("ProjectAccessLogs")
                        .HasForeignKey("ProjectApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProjectApartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectApartment", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Management", "Managements")
                        .WithMany("ProjectApartments")
                        .HasForeignKey("ManagementID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.ProjectImage", "ProjectImages")
                        .WithMany("ProjectApartments")
                        .HasForeignKey("ProjectImageID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Managements");

                    b.Navigation("ProjectImages");
                });

            modelBuilder.Entity("AVR.Domain.Entities.RequestApartment", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Apartment", "Apartments")
                        .WithMany("RequestApartments")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Customer", "Customers")
                        .WithMany("RequestApartments")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Management", "Managements")
                        .WithMany("RequestApartments")
                        .HasForeignKey("ManagementID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Apartments");

                    b.Navigation("Customers");

                    b.Navigation("Managements");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Staff", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", "Accounts")
                        .WithOne("Staffs")
                        .HasForeignKey("AVR.Domain.Entities.Staff", "AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Deposit", "Deposits")
                        .WithOne("Transactions")
                        .HasForeignKey("AVR.Domain.Entities.Transaction", "DepositID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deposits");
                });

            modelBuilder.Entity("AVR.Domain.Entities.VRExperience", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Apartment", "Apartments")
                        .WithMany("VRExperiences")
                        .HasForeignKey("ApartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Staff", "Staffs")
                        .WithMany("VRExperiences")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Apartments");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("AVR.Domain.Entities.VR_Access_Log", b =>
                {
                    b.HasOne("AVR.Domain.Entities.VRExperience", "VRExperiences")
                        .WithMany("VR_Access_Logs")
                        .HasForeignKey("VRExperienceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("VRExperiences");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.AccountRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.AccountRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AVR.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AVR.Domain.Entities.Account", b =>
                {
                    b.Navigation("ApartmentOwners")
                        .IsRequired();

                    b.Navigation("ApartmentProjectProviders")
                        .IsRequired();

                    b.Navigation("Customers")
                        .IsRequired();

                    b.Navigation("Feedbacks");

                    b.Navigation("Managements")
                        .IsRequired();

                    b.Navigation("Notifications");

                    b.Navigation("Staffs")
                        .IsRequired();
                });

            modelBuilder.Entity("AVR.Domain.Entities.Apartment", b =>
                {
                    b.Navigation("ApartmentImages");

                    b.Navigation("ApartmentInteractions");

                    b.Navigation("Appointments");

                    b.Navigation("Deposits");

                    b.Navigation("RequestApartments");

                    b.Navigation("VRExperiences");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentFacility", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentOwner", b =>
                {
                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ApartmentProjectProvider", b =>
                {
                    b.Navigation("AgreementUpdateRequests");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Customer", b =>
                {
                    b.Navigation("ApartmentInteractions");

                    b.Navigation("Appointments");

                    b.Navigation("Deposits");

                    b.Navigation("RequestApartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Deposit", b =>
                {
                    b.Navigation("DepositCancels");

                    b.Navigation("Transactions")
                        .IsRequired();
                });

            modelBuilder.Entity("AVR.Domain.Entities.DepositCancelType", b =>
                {
                    b.Navigation("DepositCancels");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Management", b =>
                {
                    b.Navigation("AgreementUpdateRequests");

                    b.Navigation("DepositCancels");

                    b.Navigation("ProjectApartments");

                    b.Navigation("RequestApartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.NotificationType", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectApartment", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("ProjectAccessLogs");
                });

            modelBuilder.Entity("AVR.Domain.Entities.ProjectImage", b =>
                {
                    b.Navigation("ProjectApartments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Slot", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("AVR.Domain.Entities.Staff", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("VRExperiences");
                });

            modelBuilder.Entity("AVR.Domain.Entities.VRExperience", b =>
                {
                    b.Navigation("VR_Access_Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
